export type Exercise = {
  id: string;
  name: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string;
  level: "beginner" | "intermediate" | "expert";
  category: string;
  force: string | null;
  mechanic: string | null;
  instructions: string[];
  images: string[];
};

export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Lie flat on a bench with your eyes under the bar. Grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it directly above your chest with arms fully extended.",
      "Lower the bar under control until it lightly touches your mid-chest.",
      "Press the bar back up to the starting position, fully extending your arms. Repeat.",
    ],
    images: [],
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Lie flat on a bench holding a dumbbell in each hand at chest level, palms facing forward.",
      "Press both dumbbells up until your arms are fully extended and the dumbbells nearly touch.",
      "Lower the dumbbells slowly back to chest level, elbows flaring at roughly 45 degrees.",
      "Repeat for the desired number of reps.",
    ],
    images: [],
  },
  {
    id: "incline-barbell-press",
    name: "Incline Barbell Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Set a bench to a 30–45 degree incline. Lie back and grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it above your upper chest with arms extended.",
      "Lower the bar slowly to your upper chest, keeping elbows at roughly 45 degrees.",
      "Press the bar back up to full arm extension. Repeat.",
    ],
    images: [],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Set a bench to a 30–45 degree incline. Sit back holding a dumbbell in each hand at shoulder height.",
      "Press the dumbbells up and together until your arms are fully extended.",
      "Lower slowly back to the starting position with control.",
      "Repeat for the desired reps.",
    ],
    images: [],
  },
  {
    id: "push-up",
    name: "Push-Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Start in a high plank with hands slightly wider than shoulder-width, body in a straight line.",
      "Lower your chest toward the floor by bending your elbows, keeping them at roughly 45 degrees from your torso.",
      "Stop just before your chest touches the floor, then push back up to the starting position.",
      "Keep your core braced and hips level throughout the movement.",
    ],
    images: [],
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Fly",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Lie flat on a bench holding a dumbbell in each hand, arms extended above your chest with a slight elbow bend.",
      "Open your arms in a wide arc, lowering the dumbbells until you feel a deep stretch in your chest.",
      "Reverse the motion, squeezing your chest to bring the dumbbells back to the starting position.",
      "Keep the slight bend in your elbows constant throughout.",
    ],
    images: [],
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Set both cable pulleys to the high position. Stand in the center, grab a handle in each hand.",
      "Step forward slightly. Start with arms wide and extended at shoulder height.",
      "Pull both handles down and together in a hugging motion until your hands meet or cross in front of your waist.",
      "Slowly return to the starting position with control. Squeeze your chest at the peak contraction.",
    ],
    images: [],
  },
  {
    id: "chest-dip",
    name: "Chest Dip",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Grip parallel dip bars and press yourself up so arms are extended. Lean your torso forward 30–45 degrees.",
      "Lower yourself by bending your elbows until your upper arms are parallel to the floor.",
      "Press back up to full arm extension, maintaining the forward lean throughout.",
      "Keep elbows slightly flared outward to bias the chest.",
    ],
    images: [],
  },
  {
    id: "pec-deck",
    name: "Pec Deck Machine",
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Adjust the seat so your arms are parallel to the floor when holding the pads. Sit with your back flat.",
      "Place your forearms on the pads and grip the handles.",
      "Bring the pads together in a controlled arc, squeezing your chest at the top.",
      "Slowly release back to the stretched starting position.",
    ],
    images: [],
  },
  {
    id: "decline-push-up",
    name: "Decline Push-Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Place your feet on an elevated surface (bench or box) and hands on the floor, slightly wider than shoulder-width.",
      "Your body should form a straight line from head to hips to feet.",
      "Lower your chest toward the floor with control, then press back up.",
      "Keep your core tight to prevent your hips from sagging.",
    ],
    images: [],
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Wedge one end of a barbell into a corner or landmine attachment. Kneel or stand in front of it.",
      "Grip the loaded end with both hands at chest height, elbows tucked.",
      "Press the bar up and away in an arc until your arms are extended.",
      "Lower the bar back to chest height with control and repeat.",
    ],
    images: [],
  },
  {
    id: "wide-push-up",
    name: "Wide Push-Up",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Get into a push-up position with hands placed wider than shoulder-width.",
      "Lower your chest straight down, keeping elbows flared wide.",
      "Push back up to the starting position, squeezing your chest at the top.",
      "Maintain a straight body line throughout the movement.",
    ],
    images: [],
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: "pull-up",
    name: "Pull-Up",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "middle back"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Hang from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width.",
      "Engage your lats and pull your chest toward the bar, leading with your elbows.",
      "Continue pulling until your chin clears the bar.",
      "Lower yourself under control back to a dead hang. Repeat.",
    ],
    images: [],
  },
  {
    id: "chin-up",
    name: "Chin-Up",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Hang from a bar with an underhand (supinated) grip, hands shoulder-width apart.",
      "Pull yourself up by driving your elbows down and back, feeling your biceps and lats engage.",
      "Raise yourself until your chin is above the bar.",
      "Lower with control to a full hang and repeat.",
    ],
    images: [],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    primaryMuscles: ["middle back"],
    secondaryMuscles: ["lats", "biceps", "lower back"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart. Hinge at the hips until your torso is roughly parallel to the floor, gripping the bar overhand.",
      "Keep your back flat and core braced. Pull the bar toward your lower chest or upper abdomen.",
      "Drive your elbows back and up, squeezing your shoulder blades together at the top.",
      "Lower the bar under control and repeat.",
    ],
    images: [],
  },
  {
    id: "dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["middle back", "biceps"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Place one knee and the same-side hand on a bench. Hold a dumbbell in your free hand, arm extended.",
      "Keep your back flat and parallel to the floor. Pull the dumbbell up toward your hip, driving your elbow back.",
      "Squeeze your lat at the top of the movement.",
      "Lower the dumbbell with control back to the starting position.",
    ],
    images: [],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "middle back"],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Sit at a lat pulldown station and secure your thighs under the pad. Grip the bar wider than shoulder-width.",
      "Lean back slightly and pull the bar down toward your upper chest, driving your elbows down and back.",
      "Squeeze your lats at the bottom of the movement.",
      "Slowly let the bar rise back to the starting position with full arm extension.",
    ],
    images: [],
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    primaryMuscles: ["middle back"],
    secondaryMuscles: ["lats", "biceps"],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Sit at a cable row station, feet on the platform, knees slightly bent. Grip the handle.",
      "Sit upright with a flat back. Pull the handle toward your abdomen, driving your elbows past your torso.",
      "Squeeze your shoulder blades together at the peak contraction.",
      "Extend your arms fully, letting your back stretch forward slightly, then repeat.",
    ],
    images: [],
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    primaryMuscles: ["lower back"],
    secondaryMuscles: ["hamstrings", "glutes", "traps", "middle back"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Stand with feet hip-width apart, the bar over your mid-foot. Hinge down and grip the bar just outside your legs.",
      "Set your back flat, chest up, and hips down. Take a deep breath and brace your core.",
      "Drive your feet through the floor, extending hips and knees simultaneously to lift the bar.",
      "Lock out at the top — hips and knees fully extended, standing tall. Hinge back down to lower the bar.",
    ],
    images: [],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["middle back", "traps"],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Set a cable pulley to upper-chest or face height. Attach a rope handle and grip with both hands, palms facing in.",
      "Step back until there is tension on the cable. Stand with feet shoulder-width apart.",
      "Pull the rope toward your face, separating your hands and driving your elbows wide and back.",
      "Hold the peak contraction for a beat, then extend your arms and repeat.",
    ],
    images: [],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    primaryMuscles: ["middle back"],
    secondaryMuscles: ["lats", "biceps", "lower back"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Wedge a barbell into a corner or use a T-bar row station. Straddle the bar with a flat back.",
      "Grip the handles and hinge forward until your torso is roughly 45 degrees to the floor.",
      "Row the bar toward your chest, squeezing your shoulder blades together at the top.",
      "Lower under control until your arms are fully extended, then repeat.",
    ],
    images: [],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    primaryMuscles: ["middle back"],
    secondaryMuscles: ["lats", "biceps"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Set a bar in a rack at waist height. Lie underneath it and grip with an overhand grip.",
      "Keep your body in a straight line from head to heels, heels on the floor.",
      "Pull your chest up to the bar by driving your elbows back and squeezing your shoulder blades.",
      "Lower yourself back to the starting position with control.",
    ],
    images: [],
  },
  {
    id: "hyperextension",
    name: "Back Extension",
    primaryMuscles: ["lower back"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Position yourself on a hyperextension bench, pads just below your hip bones. Cross arms over your chest.",
      "Hinge at the hips and lower your torso toward the floor under control.",
      "Raise your torso back up until your body forms a straight line — do not hyperextend.",
      "Squeeze your glutes and lower back at the top. Repeat.",
    ],
    images: [],
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Stand at a high cable pulley with a straight bar or rope. Hold with arms extended at shoulder height.",
      "Keep your arms nearly straight (slight bend at elbows). Hinge slightly at the hips.",
      "Pull the bar down in an arc toward your thighs, squeezing your lats at the bottom.",
      "Slowly return to the starting position with full lat stretch.",
    ],
    images: [],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    primaryMuscles: ["lower back"],
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart, a barbell resting on your upper traps.",
      "Hinge at the hips, pushing them back while maintaining a flat back and soft knees.",
      "Lower your torso until it is roughly parallel to the floor, feeling a stretch in your hamstrings.",
      "Drive your hips forward to return to the starting position.",
    ],
    images: [],
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: "overhead-barbell-press",
    name: "Overhead Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "traps"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart. Hold the barbell at shoulder height with an overhand grip.",
      "Brace your core and glutes. Press the bar directly overhead until your arms are fully locked out.",
      "Bring the bar back down to shoulder height under control.",
      "Keep your core tight to avoid excessive lower back arch.",
    ],
    images: [],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Sit on a bench with back support. Hold a dumbbell in each hand at shoulder height, palms forward.",
      "Press both dumbbells up and slightly together until arms are fully extended.",
      "Lower the dumbbells back to shoulder height with control.",
      "Repeat for the desired reps.",
    ],
    images: [],
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Stand with feet shoulder-width apart, a dumbbell in each hand at your sides.",
      "With a slight bend in your elbows, raise both arms out to the sides until they reach shoulder height.",
      "Keep your thumbs slightly lower than your pinkies (tilt the dumbbells like pouring water).",
      "Lower the dumbbells slowly and repeat.",
    ],
    images: [],
  },
  {
    id: "front-raise",
    name: "Front Raise",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["chest"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Stand holding a dumbbell in each hand in front of your thighs, palms facing your body.",
      "With a slight elbow bend, raise one or both arms straight in front of you to shoulder height.",
      "Hold for a moment at the top, then lower slowly to the starting position.",
      "Alternate arms or perform simultaneously.",
    ],
    images: [],
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["middle back", "traps"],
    equipment: "dumbbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Sit on the edge of a bench and lean forward until your chest rests near your thighs. Hold a dumbbell in each hand.",
      "With a slight bend in your elbows, raise both arms out to the sides, leading with your elbows.",
      "Lift until your arms are roughly parallel to the floor, squeezing your rear delts.",
      "Lower slowly to the starting position and repeat.",
    ],
    images: [],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Set a cable pulley to the low position. Stand sideways to the machine and grip the handle with your far hand.",
      "Keeping your arm nearly straight, raise it out to the side until it reaches shoulder height.",
      "Lower the cable slowly back to the starting position with control.",
      "Complete all reps on one side, then switch.",
    ],
    images: [],
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Sit on a bench with back support. Hold dumbbells at chin height, palms facing you, elbows close together.",
      "As you press the dumbbells up, rotate your forearms outward so your palms face forward at the top.",
      "Continue pressing until arms are fully extended overhead.",
      "Reverse the rotation as you lower back to the starting position.",
    ],
    images: [],
  },
  {
    id: "upright-row",
    name: "Upright Row",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["shoulders"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Stand holding a barbell with an overhand grip, hands about shoulder-width or slightly narrower.",
      "Pull the bar straight up close to your body, leading with your elbows.",
      "Raise until the bar is near chin height and elbows are above the bar.",
      "Lower slowly to the starting position and repeat.",
    ],
    images: [],
  },
  {
    id: "kettlebell-press",
    name: "Kettlebell Overhead Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "traps"],
    equipment: "kettlebells",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Clean a kettlebell to the rack position: elbow tucked, bell resting on the outside of your forearm at shoulder height.",
      "Press the kettlebell overhead until your arm is fully extended and bicep is near your ear.",
      "Lower the kettlebell back to the rack position with control.",
      "Complete all reps on one side, then switch.",
    ],
    images: [],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Adjust the seat so the handles are at shoulder height. Sit with your back against the pad.",
      "Grip the handles with palms facing forward or inward depending on the machine.",
      "Press the handles straight up until your arms are nearly extended.",
      "Lower slowly back to the starting position and repeat.",
    ],
    images: [],
  },

  // ── BICEPS ─────────────────────────────────────────────────────────────────
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Stand with feet shoulder-width apart. Hold a barbell with an underhand grip, hands shoulder-width apart.",
      "Keeping your elbows pinned at your sides, curl the bar up toward your chest.",
      "Squeeze your biceps at the top of the movement.",
      "Lower the bar slowly back to the starting position.",
    ],
    images: [],
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Stand holding a dumbbell in each hand at your sides, palms facing forward.",
      "Keeping your upper arms stationary, curl both dumbbells up toward your shoulders.",
      "Squeeze your biceps at the top, then lower slowly back down.",
      "You can alternate arms or curl both simultaneously.",
    ],
    images: [],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Stand holding a dumbbell in each hand with a neutral grip (palms facing each other).",
      "Keeping your elbows at your sides, curl both dumbbells up toward your shoulders.",
      "Hold the contraction at the top, then lower with control.",
      "This grip targets the brachialis and brachioradialis more than a supinated curl.",
    ],
    images: [],
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Sit at a preacher curl bench and rest the backs of your upper arms flat on the angled pad.",
      "Grip an EZ-bar or barbell with an underhand grip.",
      "Curl the weight up until your forearms are nearly vertical, then lower slowly to full extension.",
      "Do not swing or use momentum — keep strict form.",
    ],
    images: [],
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Sit on a bench with feet wide. Hold a dumbbell in one hand and brace that arm against your inner thigh.",
      "Starting with your arm extended, curl the dumbbell up toward your shoulder.",
      "Squeeze hard at the top, then lower slowly.",
      "Complete all reps, then switch arms.",
    ],
    images: [],
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Set a cable pulley to the low position. Attach a straight bar or EZ-bar. Stand facing the machine.",
      "Grip the bar with an underhand grip, elbows pinned at your sides.",
      "Curl the bar up toward your chest, squeezing your biceps at the top.",
      "Lower slowly back to full arm extension.",
    ],
    images: [],
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Set a bench to a 45–60 degree incline. Sit back with a dumbbell in each hand, arms hanging straight down.",
      "Curl both dumbbells up while keeping your upper arms stationary and perpendicular to the floor.",
      "Squeeze at the top, then lower slowly to full extension.",
      "The incline position increases the stretch on the biceps long head.",
    ],
    images: [],
  },
  {
    id: "reverse-curl",
    name: "Reverse Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Stand holding a barbell with an overhand (pronated) grip, hands shoulder-width apart.",
      "Keeping elbows at your sides, curl the bar toward your shoulders.",
      "Lower with control back to the starting position.",
      "The overhand grip heavily targets the brachioradialis and forearm extensors.",
    ],
    images: [],
  },

  // ── TRICEPS ────────────────────────────────────────────────────────────────
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Set a cable pulley to the high position and attach a straight bar or rope. Stand facing the machine.",
      "Grip the attachment and tuck your elbows to your sides. Start with forearms parallel to the floor.",
      "Push the bar down until your arms are fully extended, squeezing your triceps at the bottom.",
      "Allow the bar to rise back slowly to the starting position.",
    ],
    images: [],
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Lie flat on a bench holding an EZ-bar or barbell with a narrow overhand grip, arms extended above your chest.",
      "Keeping your upper arms vertical, bend your elbows and lower the bar toward your forehead.",
      "Stop just before the bar touches your head, then extend your arms back to the starting position.",
      "Keep your upper arms perfectly still throughout the movement.",
    ],
    images: [],
  },
  {
    id: "overhead-tricep-extension",
    name: "Overhead Tricep Extension",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Sit or stand holding one dumbbell with both hands, cupped under the inner plate.",
      "Press the dumbbell overhead so your arms are extended. Keep your upper arms next to your ears.",
      "Bend your elbows and lower the dumbbell behind your head until you feel a stretch.",
      "Extend your arms back to the starting position, squeezing your triceps at the top.",
    ],
    images: [],
  },
  {
    id: "tricep-dip",
    name: "Tricep Dip",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Sit on the edge of a bench, hands gripping the edge beside your hips. Extend your legs out in front.",
      "Lower yourself by bending your elbows to roughly 90 degrees, keeping your back close to the bench.",
      "Press yourself back up to the starting position, fully extending your arms.",
      "For more difficulty, elevate your feet on another bench.",
    ],
    images: [],
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Lie flat on a bench. Grip the bar with hands about shoulder-width apart (or slightly narrower).",
      "Unrack the bar and lower it to your mid-chest while keeping your elbows tucked close to your body.",
      "Press the bar back up to full arm extension.",
      "The narrow grip shifts emphasis from the chest to the triceps.",
    ],
    images: [],
  },
  {
    id: "dumbbell-kickback",
    name: "Tricep Kickback",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Hinge forward with a flat back, holding a dumbbell in one hand. Bring your upper arm parallel to the floor.",
      "Keeping your upper arm stationary, extend your forearm straight back until your arm is fully extended.",
      "Squeeze your tricep at full extension, then bend your elbow to return.",
      "Complete all reps on one side, then switch.",
    ],
    images: [],
  },
  {
    id: "rope-pushdown",
    name: "Rope Pushdown",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Attach a rope to a high cable pulley. Grip the rope with both hands, thumbs facing up.",
      "Tuck your elbows at your sides and start with forearms parallel to the floor.",
      "Push the rope down, spreading the ends apart at the bottom for full tricep contraction.",
      "Slowly return to the starting position and repeat.",
    ],
    images: [],
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-Up",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Get into a push-up position and place your hands together under your chest, forming a diamond shape with thumbs and index fingers.",
      "Keep your body in a straight line and lower your chest toward your hands.",
      "Push back up to full arm extension, keeping elbows close to your body.",
      "This variation is harder than a standard push-up due to the narrow base.",
    ],
    images: [],
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: "barbell-squat",
    name: "Barbell Back Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings", "lower back"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand in a squat rack with the bar resting on your upper traps. Feet shoulder to hip-width apart, toes turned slightly out.",
      "Take a breath, brace your core, then descend by breaking at the hips and knees simultaneously.",
      "Lower until your thighs are at least parallel to the floor, keeping your chest up and knees tracking over your toes.",
      "Drive through your heels to stand back up to the starting position.",
    ],
    images: [],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "lower back"],
    equipment: "barbell",
    level: "expert",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Rest the barbell on your front delts and collarbone with elbows pointing forward. Feet shoulder-width apart.",
      "Keep your torso very upright as you descend — this is essential in the front squat.",
      "Squat down until thighs are parallel or below, keeping elbows high throughout.",
      "Drive up through your heels, maintaining your upright posture.",
    ],
    images: [],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "kettlebells",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Hold a kettlebell by the horns at chest height. Stand with feet shoulder-width apart, toes slightly out.",
      "Squat down between your knees, keeping the kettlebell close to your chest and elbows inside your knees.",
      "Lower until your thighs are parallel or below, keeping your chest tall.",
      "Press through your heels and stand back up.",
    ],
    images: [],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Sit in the leg press machine with your back flat against the pad. Place feet shoulder-width apart on the platform.",
      "Release the safety handles and lower the platform by bending your knees toward your chest.",
      "Stop before your lower back rounds off the seat, then press the platform back to near full extension.",
      "Do not lock your knees out at the top.",
    ],
    images: [],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand a few feet in front of a bench. Place the top of one foot on the bench behind you.",
      "Hold a dumbbell in each hand. Lower your back knee toward the floor by bending your front knee.",
      "Keep your front shin mostly vertical and torso upright.",
      "Press through your front heel to return to standing. Complete all reps, then switch legs.",
    ],
    images: [],
  },
  {
    id: "lunge",
    name: "Forward Lunge",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet together. Step one foot forward into a lunge position.",
      "Lower your back knee toward the floor until both knees are at roughly 90 degrees.",
      "Push off your front foot to return to the starting position.",
      "Alternate legs or complete all reps on one side first.",
    ],
    images: [],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower back"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Stand holding a barbell at hip height with an overhand grip. Feet hip-width apart.",
      "Hinge at the hips, pushing them back as you lower the bar along your legs. Keep your back flat.",
      "Lower until you feel a deep stretch in your hamstrings — typically mid-shin level for most people.",
      "Drive your hips forward to stand back up, squeezing your glutes at the top.",
    ],
    images: [],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Sit in the leg extension machine with the pad resting just above your feet. Back flat against the seat.",
      "Extend your legs until they are straight and parallel to the floor.",
      "Squeeze your quads hard at the top, then lower slowly back to the starting position.",
      "Avoid using momentum.",
    ],
    images: [],
  },
  {
    id: "leg-curl",
    name: "Lying Leg Curl",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Lie face-down on a leg curl machine with the pad just above your heels.",
      "Curl your legs up toward your glutes by bending your knees.",
      "Squeeze your hamstrings at the top of the movement.",
      "Lower your legs slowly back to the starting position.",
    ],
    images: [],
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Stand on the edge of a step or flat ground with feet hip-width apart.",
      "Rise up onto the balls of your feet as high as possible.",
      "Hold for a moment at the top, then lower your heels below the step for a full stretch.",
      "Repeat. For added resistance, hold dumbbells or use a calf raise machine.",
    ],
    images: [],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Sit in a seated calf raise machine with the pads resting on your lower thighs, just above your knees.",
      "Place the balls of your feet on the platform, heels hanging off.",
      "Rise up onto the balls of your feet as high as possible, then lower below the platform level.",
      "Perform slow, controlled reps through the full range of motion.",
    ],
    images: [],
  },
  {
    id: "step-up",
    name: "Dumbbell Step-Up",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand in front of a bench or box holding a dumbbell in each hand.",
      "Step one foot onto the bench and drive through that heel to lift your body up.",
      "Bring your trailing leg up to standing on the bench, then step back down.",
      "Alternate legs or complete all reps on one side.",
    ],
    images: [],
  },
  {
    id: "sumo-squat",
    name: "Sumo Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "adductors"],
    equipment: "dumbbell",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet wider than shoulder-width, toes pointed out at roughly 45 degrees. Hold one dumbbell with both hands.",
      "Squat down between your legs, keeping your chest tall and knees tracking over your toes.",
      "Lower until your thighs are parallel to the floor, then press back up.",
      "Squeeze your glutes and adductors at the top.",
    ],
    images: [],
  },
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    equipment: "body only",
    level: "expert",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Kneel on a soft surface with your feet anchored under a bar or held by a partner.",
      "Keeping your body straight from knees to head, lower yourself forward as slowly as possible.",
      "Use your hands to catch yourself at the bottom, then pull yourself back up using your hamstrings.",
      "This is a highly demanding exercise — build up gradually.",
    ],
    images: [],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "machine",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Position yourself in the hack squat machine with your back against the pad and shoulders under the handles.",
      "Release the safety handles and descend by bending your knees toward your chest.",
      "Lower until your thighs reach parallel or below, then press back up.",
      "Keep your feet shoulder-width apart and toes slightly out.",
    ],
    images: [],
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders", "lower back"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: null,
    mechanic: "isolation",
    instructions: [
      "Get into a forearm plank position: elbows under shoulders, forearms flat, toes on the floor.",
      "Keep your body in a perfectly straight line from head to heels.",
      "Brace your abs hard, squeeze your glutes, and breathe normally.",
      "Hold for the target duration without letting your hips sag or pike.",
    ],
    images: [],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: null,
    mechanic: "isolation",
    instructions: [
      "Lie on your side with one forearm on the floor directly under your shoulder.",
      "Stack your feet or stagger them. Lift your hips so your body forms a straight line.",
      "Hold this position, keeping your hips elevated and core braced.",
      "Switch sides and repeat.",
    ],
    images: [],
  },
  {
    id: "crunch",
    name: "Crunch",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: [],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Lie on your back with knees bent, feet flat on the floor. Cross your arms over your chest or place hands lightly behind your head.",
      "Engage your abs and curl your shoulders off the floor, bringing your chest toward your knees.",
      "Hold briefly at the top, then lower slowly back down. Do not pull on your neck.",
      "Exhale as you crunch up, inhale as you lower.",
    ],
    images: [],
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: [],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Lie on your back with hands lightly behind your head, legs elevated and knees bent to 90 degrees.",
      "Bring your right elbow toward your left knee while extending your right leg.",
      "Switch sides in a pedaling motion — left elbow to right knee.",
      "Move in a controlled rhythm, focusing on rotating the torso rather than pulling with your neck.",
    ],
    images: [],
  },
  {
    id: "leg-raise",
    name: "Lying Leg Raise",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["hip flexors"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Lie flat on your back with legs extended and hands under your lower back for support.",
      "Keeping legs straight (or slightly bent), raise them toward the ceiling until they are vertical.",
      "Lower slowly back down, stopping just before your heels touch the floor.",
      "Repeat, keeping your lower back pressed into the floor throughout.",
    ],
    images: [],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["hip flexors", "lats"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Hang from a pull-up bar with an overhand grip, arms fully extended.",
      "Brace your core and raise your legs until they are parallel to the floor (or higher).",
      "Hold briefly at the top, then lower your legs slowly back down.",
      "Avoid swinging — use core strength throughout.",
    ],
    images: [],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: [],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Sit on the floor with knees bent and feet slightly elevated. Lean back so your torso is at roughly 45 degrees.",
      "Clasp your hands together in front of you. Rotate your torso to one side, bringing your hands toward the floor.",
      "Rotate to the other side in a controlled motion.",
      "For added difficulty, hold a weight plate or medicine ball.",
    ],
    images: [],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders", "lower back"],
    equipment: "body only",
    level: "expert",
    category: "strength",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Kneel on the floor holding an ab wheel with both hands, directly under your shoulders.",
      "Brace your core and roll the wheel forward, extending your body as far as you can without your hips sagging.",
      "Pull the wheel back toward your knees using your abs to return to the starting position.",
      "Start with short rolls and increase range of motion as you get stronger.",
    ],
    images: [],
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: [],
    equipment: "cable",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Attach a rope to a high cable pulley. Kneel in front of the machine and hold the rope behind your head.",
      "With hips stationary, crunch your elbows toward your knees, rounding your back.",
      "Hold the peak contraction, then slowly extend back to the starting position.",
      "Focus on using your abs, not your hip flexors.",
    ],
    images: [],
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders", "hip flexors"],
    equipment: "body only",
    level: "beginner",
    category: "cardio",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Start in a high push-up position with your core braced.",
      "Drive one knee toward your chest, then quickly switch legs in a running motion.",
      "Keep your hips level and your back flat — do not let them rise or sag.",
      "Maintain a steady, controlled pace or go faster for a cardio effect.",
    ],
    images: [],
  },
  {
    id: "v-up",
    name: "V-Up",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["hip flexors"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "isolation",
    instructions: [
      "Lie flat on your back with arms extended overhead and legs straight.",
      "Simultaneously raise your legs and torso off the floor, reaching your hands toward your feet.",
      "Your body should form a 'V' shape at the top.",
      "Lower back down with control and repeat.",
    ],
    images: [],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["lower back"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: null,
    mechanic: "isolation",
    instructions: [
      "Lie on your back with arms pointing toward the ceiling and knees bent at 90 degrees, shins parallel to the floor.",
      "Brace your core and press your lower back into the floor.",
      "Slowly lower your right arm and left leg toward the floor while keeping the opposite arm and leg still.",
      "Return to center and repeat on the other side. Never let your lower back arch off the floor.",
    ],
    images: [],
  },

  // ── GLUTES ─────────────────────────────────────────────────────────────────
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Sit with your upper back against a bench, a barbell resting across your hips. Feet flat on the floor, hip-width apart.",
      "Drive through your heels to thrust your hips upward until your body forms a straight line from knees to shoulders.",
      "Squeeze your glutes hard at the top and hold for a beat.",
      "Lower your hips back down and repeat.",
    ],
    images: [],
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Lie on your back with knees bent and feet flat on the floor, hip-width apart.",
      "Drive your heels into the floor and squeeze your glutes to raise your hips toward the ceiling.",
      "Hold the top position for 1–2 seconds, then lower back down.",
      "For added resistance, place a dumbbell or plate on your hips.",
    ],
    images: [],
  },
  {
    id: "cable-kickback",
    name: "Cable Glute Kickback",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "cable",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Attach an ankle cuff to a low cable pulley. Secure it to one ankle and face the machine.",
      "Hold the machine for balance. Kick your leg straight back, squeezing your glute at the top.",
      "Keep a slight bend in the working knee and avoid rotating your hips.",
      "Lower the leg with control and repeat. Switch legs.",
    ],
    images: [],
  },
  {
    id: "donkey-kick",
    name: "Donkey Kick",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "body only",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Start on all fours with wrists under shoulders and knees under hips.",
      "Keeping your knee bent at 90 degrees, drive one heel toward the ceiling.",
      "Squeeze your glute at the top, then lower your knee back toward the floor without touching.",
      "Complete all reps on one side, then switch.",
    ],
    images: [],
  },
  {
    id: "single-leg-hip-thrust",
    name: "Single-Leg Hip Thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "body only",
    level: "intermediate",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Set up as for a regular glute bridge but extend one leg straight out in front of you.",
      "Drive through the heel of the planted foot to thrust your hips upward.",
      "Keep your extended leg in line with your body at the top.",
      "Lower and repeat. Switch legs after completing your target reps.",
    ],
    images: [],
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "quadriceps", "lower back", "adductors"],
    equipment: "barbell",
    level: "intermediate",
    category: "strength",
    force: "pull",
    mechanic: "compound",
    instructions: [
      "Stand with feet wider than shoulder-width, toes pointed well out. The bar is over your mid-foot.",
      "Hinge down and grip the bar with hands inside your legs. Set your back flat, hips low, chest up.",
      "Drive your feet out into the floor and extend your hips to lift the bar. Bar travels straight up close to your legs.",
      "Lock out at the top with hips fully extended, then hinge back down to lower the bar.",
    ],
    images: [],
  },
  {
    id: "banded-clamshell",
    name: "Banded Clamshell",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["abductors"],
    equipment: "bands",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Place a resistance band just above your knees. Lie on your side with hips and knees bent to about 45 degrees.",
      "Keeping your feet together, rotate your top knee upward like a clamshell opening.",
      "Hold at the top for a beat, squeezing your glute, then lower with control.",
      "Complete all reps, then flip over and work the other side.",
    ],
    images: [],
  },
  {
    id: "glute-kickback-machine",
    name: "Glute Kickback Machine",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "machine",
    level: "beginner",
    category: "strength",
    force: "push",
    mechanic: "isolation",
    instructions: [
      "Adjust the machine and place one foot on the kick plate. Hold the handles for stability.",
      "Drive your foot backward and upward, squeezing your glute at full extension.",
      "Hold briefly at the peak, then lower the weight with control.",
      "Complete all reps on one side, then switch.",
    ],
    images: [],
  },

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  {
    id: "burpee",
    name: "Burpee",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["chest", "shoulders", "quadriceps"],
    equipment: "body only",
    level: "intermediate",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart. Drop into a squat and place your hands on the floor.",
      "Jump or step your feet back into a push-up position.",
      "Perform one push-up, then jump or step your feet back to the squat position.",
      "Explosively jump upward with arms overhead. Land softly and repeat.",
    ],
    images: [],
  },
  {
    id: "box-jump",
    name: "Box Jump",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "calves"],
    equipment: "body only",
    level: "intermediate",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand in front of a sturdy box or platform. Feet shoulder-width apart.",
      "Dip into a quarter squat, swing your arms back, then explosively jump onto the box.",
      "Land softly with both feet fully on the box and knees slightly bent to absorb impact.",
      "Step back down one foot at a time. Reset and repeat.",
    ],
    images: [],
  },
  {
    id: "jumping-jack",
    name: "Jumping Jack",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["shoulders", "calves"],
    equipment: "body only",
    level: "beginner",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet together and arms at your sides.",
      "Jump your feet out to shoulder-width while simultaneously raising your arms overhead.",
      "Jump back to the starting position with feet together and arms down.",
      "Repeat in a continuous rhythm at a moderate to fast pace.",
    ],
    images: [],
  },
  {
    id: "high-knees",
    name: "High Knees",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["quadriceps", "calves"],
    equipment: "body only",
    level: "beginner",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet hip-width apart. Begin jogging in place.",
      "Drive each knee up toward your chest alternately, aiming to get thighs parallel to the floor.",
      "Pump your arms in rhythm with your legs.",
      "Maintain a quick pace for the desired duration.",
    ],
    images: [],
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower back", "abdominals"],
    equipment: "kettlebells",
    level: "beginner",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart, kettlebell on the floor in front of you. Hinge and grab it.",
      "Hike the kettlebell between your legs, then explosively drive your hips forward to swing it to chest height.",
      "Let the kettlebell fall and hinge your hips back to receive its weight, maintaining a flat back.",
      "Repeat in a fluid, powerful motion — the swing is hip-driven, not a squat.",
    ],
    images: [],
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    primaryMuscles: ["calves"],
    secondaryMuscles: ["abdominals", "shoulders"],
    equipment: "body only",
    level: "beginner",
    category: "cardio",
    force: null,
    mechanic: "compound",
    instructions: [
      "Hold a jump rope handle in each hand. Stand with feet together.",
      "Swing the rope over your head and jump over it with both feet as it reaches the floor.",
      "Land softly on the balls of your feet with a slight bend in your knees.",
      "Maintain a consistent rhythm. Start with basic jumps and progress to alternating feet or double-unders.",
    ],
    images: [],
  },
  {
    id: "squat-jump",
    name: "Squat Jump",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "calves"],
    equipment: "body only",
    level: "beginner",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Stand with feet shoulder-width apart. Descend into a squat.",
      "From the bottom of the squat, explode upward as high as you can.",
      "Land softly with knees bent, immediately going back into the next squat.",
      "Keep your chest up and core braced throughout.",
    ],
    images: [],
  },
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["abdominals", "biceps", "traps"],
    equipment: "bands",
    level: "intermediate",
    category: "cardio",
    force: "push",
    mechanic: "compound",
    instructions: [
      "Anchor two heavy ropes around a fixed point. Hold one end in each hand.",
      "Hinge slightly at the hips and knees in an athletic stance.",
      "Rapidly alternate raising and slamming each arm to create alternating waves in the ropes.",
      "Maintain the effort for the target duration. You can also do bilateral slams for variety.",
    ],
    images: [],
  },
];
