export type MealDBCategory = "breakfast" | "lunch" | "gas_station" | "snacks" | "dinner" | "drinks";

export type MealDBEntry = {
  name: string;
  category: MealDBCategory;
  cal: number;
  protein: number;
  carbs: number;
  fat: number;
  serving: string;
  source: string;
};

export const MEAL_DB: MealDBEntry[] = [
  // ─── BREAKFAST ────────────────────────────────────────────────────────────
  { name: "Breakfast Burrito (egg, sausage, cheese)", category: "breakfast", cal: 480, protein: 22, carbs: 48, fat: 20, serving: "1 burrito", source: "Home / food truck" },
  { name: "McDonald's Egg McMuffin", category: "breakfast", cal: 300, protein: 17, carbs: 30, fat: 12, serving: "1 sandwich", source: "McDonald's" },
  { name: "McDonald's Sausage McGriddle", category: "breakfast", cal: 550, protein: 15, carbs: 48, fat: 28, serving: "1 sandwich", source: "McDonald's" },
  { name: "McDonald's Sausage, Egg & Cheese McGriddle", category: "breakfast", cal: 620, protein: 20, carbs: 49, fat: 34, serving: "1 sandwich", source: "McDonald's" },
  { name: "McDonald's Steak, Egg & Cheese Bagel", category: "breakfast", cal: 620, protein: 37, carbs: 55, fat: 28, serving: "1 sandwich", source: "McDonald's" },
  { name: "McDonald's Bacon, Egg & Cheese Biscuit", category: "breakfast", cal: 460, protein: 19, carbs: 38, fat: 26, serving: "1 biscuit", source: "McDonald's" },
  { name: "Dunkin' Egg & Cheese on Croissant", category: "breakfast", cal: 370, protein: 14, carbs: 30, fat: 22, serving: "1 sandwich", source: "Dunkin'" },
  { name: "Dunkin' Sausage, Egg & Cheese Wake-Up Wrap", category: "breakfast", cal: 290, protein: 14, carbs: 22, fat: 16, serving: "1 wrap", source: "Dunkin'" },
  { name: "Chick-fil-A Chicken Biscuit", category: "breakfast", cal: 440, protein: 20, carbs: 49, fat: 19, serving: "1 biscuit", source: "Chick-fil-A" },
  { name: "Chick-fil-A Egg White Grill", category: "breakfast", cal: 290, protein: 26, carbs: 30, fat: 7, serving: "1 sandwich", source: "Chick-fil-A" },
  { name: "Chick-fil-A Hash Brown Scramble Burrito", category: "breakfast", cal: 700, protein: 30, carbs: 63, fat: 36, serving: "1 burrito", source: "Chick-fil-A" },
  { name: "Waffle House Waffle + 2 Eggs + Bacon", category: "breakfast", cal: 760, protein: 24, carbs: 72, fat: 38, serving: "1 combo", source: "Waffle House" },
  { name: "Denny's Grand Slam", category: "breakfast", cal: 820, protein: 38, carbs: 68, fat: 44, serving: "1 combo", source: "Denny's" },
  { name: "Gas Station Breakfast Sandwich (egg, cheese, sausage)", category: "breakfast", cal: 350, protein: 16, carbs: 28, fat: 18, serving: "1 sandwich", source: "Gas station" },
  { name: "Wawa Sizzli (egg, cheese, bacon)", category: "breakfast", cal: 390, protein: 19, carbs: 33, fat: 20, serving: "1 sandwich", source: "Wawa" },
  { name: "Sheetz MTO Breakfast Sandwich", category: "breakfast", cal: 530, protein: 25, carbs: 40, fat: 28, serving: "1 sandwich", source: "Sheetz" },
  { name: "Jimmy Dean Breakfast Bowl (frozen)", category: "breakfast", cal: 350, protein: 16, carbs: 26, fat: 20, serving: "1 bowl", source: "Gas station / store" },
  { name: "Jimmy Dean Sausage Egg & Cheese Muffin", category: "breakfast", cal: 340, protein: 15, carbs: 30, fat: 18, serving: "1 sandwich", source: "Gas station / store" },
  { name: "Bagel with Cream Cheese", category: "breakfast", cal: 380, protein: 11, carbs: 58, fat: 12, serving: "1 bagel", source: "Bakery / gas station" },
  { name: "Bagel with Peanut Butter", category: "breakfast", cal: 410, protein: 16, carbs: 56, fat: 14, serving: "1 bagel", source: "Bakery / gas station" },
  { name: "Greek Yogurt Parfait (granola + fruit)", category: "breakfast", cal: 290, protein: 16, carbs: 44, fat: 6, serving: "1 cup", source: "Gas station / Dunkin'" },
  { name: "Instant Oatmeal Packet", category: "breakfast", cal: 130, protein: 4, carbs: 26, fat: 2, serving: "1 packet", source: "Home / store" },
  { name: "Overnight Oats (oats, milk, protein powder)", category: "breakfast", cal: 380, protein: 25, carbs: 48, fat: 8, serving: "1 jar", source: "Home meal prep" },
  { name: "Protein Shake (premix, Muscle Milk)", category: "breakfast", cal: 160, protein: 25, carbs: 8, fat: 5, serving: "1 bottle (11oz)", source: "Gas station / store" },
  { name: "Hard Boiled Eggs (2)", category: "breakfast", cal: 140, protein: 12, carbs: 1, fat: 10, serving: "2 eggs", source: "Gas station / home" },
  { name: "Quest Protein Bar", category: "breakfast", cal: 200, protein: 21, carbs: 22, fat: 7, serving: "1 bar (2.1oz)", source: "Gas station / store" },
  { name: "RXBar (chocolate sea salt)", category: "breakfast", cal: 210, protein: 12, carbs: 24, fat: 9, serving: "1 bar (1.83oz)", source: "Gas station / store" },
  { name: "Pop-Tarts (2-pack, frosted strawberry)", category: "breakfast", cal: 380, protein: 4, carbs: 74, fat: 8, serving: "2 pastries", source: "Gas station / store" },
  { name: "Banana + Peanut Butter (2 tbsp)", category: "breakfast", cal: 330, protein: 9, carbs: 42, fat: 14, serving: "1 banana + 2 tbsp", source: "Home / store" },
  { name: "Kodiak Cakes Protein Waffles (2)", category: "breakfast", cal: 360, protein: 24, carbs: 48, fat: 8, serving: "2 waffles", source: "Home / store" },
  { name: "Protein Pancakes (2, Kodiak mix)", category: "breakfast", cal: 280, protein: 22, carbs: 38, fat: 5, serving: "2 pancakes", source: "Home" },
  { name: "Eggs Scrambled (2) + Toast", category: "breakfast", cal: 320, protein: 16, carbs: 30, fat: 14, serving: "2 eggs + 1 slice", source: "Home / diner" },
  { name: "Breakfast Taco (egg, cheese, sausage, flour tortilla)", category: "breakfast", cal: 320, protein: 14, carbs: 30, fat: 16, serving: "1 taco", source: "Food truck / home" },
  { name: "Granola Bar (Quaker Oats & Honey)", category: "breakfast", cal: 190, protein: 4, carbs: 35, fat: 5, serving: "1 bar (1.5oz)", source: "Gas station / store" },
  { name: "Sausage Biscuit (gas station / fast food)", category: "breakfast", cal: 430, protein: 13, carbs: 36, fat: 26, serving: "1 biscuit", source: "McDonald's / gas station" },
  { name: "Milk + Protein Powder Shake", category: "breakfast", cal: 270, protein: 35, carbs: 18, fat: 6, serving: "1 shaker (16oz)", source: "Home" },
  { name: "Egg & Cheese Wrap (homemade)", category: "breakfast", cal: 260, protein: 17, carbs: 24, fat: 10, serving: "1 wrap", source: "Home" },
  { name: "Fruit Smoothie (banana, strawberry, Greek yogurt)", category: "breakfast", cal: 290, protein: 10, carbs: 52, fat: 3, serving: "16oz", source: "Home / Smoothie King" },
  { name: "Cottage Cheese + Fruit (1/2 cup)", category: "breakfast", cal: 150, protein: 14, carbs: 14, fat: 3, serving: "1/2 cup + fruit", source: "Home" },
  { name: "Cereal with 2% Milk (1 bowl)", category: "breakfast", cal: 270, protein: 10, carbs: 48, fat: 5, serving: "1 bowl", source: "Home" },

  // ─── LUNCH / BREAK ────────────────────────────────────────────────────────
  { name: "Subway Turkey Breast 6-inch", category: "lunch", cal: 280, protein: 22, carbs: 40, fat: 4, serving: "6-inch sub", source: "Subway" },
  { name: "Subway Rotisserie Chicken 6-inch", category: "lunch", cal: 350, protein: 32, carbs: 40, fat: 7, serving: "6-inch sub", source: "Subway" },
  { name: "Subway Italian BMT 6-inch", category: "lunch", cal: 410, protein: 22, carbs: 40, fat: 18, serving: "6-inch sub", source: "Subway" },
  { name: "Subway Meatball Marinara 6-inch", category: "lunch", cal: 480, protein: 20, carbs: 58, fat: 18, serving: "6-inch sub", source: "Subway" },
  { name: "Subway Turkey Breast Footlong", category: "lunch", cal: 560, protein: 44, carbs: 80, fat: 8, serving: "12-inch sub", source: "Subway" },
  { name: "McDonald's Big Mac", category: "lunch", cal: 550, protein: 25, carbs: 46, fat: 30, serving: "1 burger", source: "McDonald's" },
  { name: "McDonald's Quarter Pounder with Cheese", category: "lunch", cal: 520, protein: 30, carbs: 42, fat: 26, serving: "1 burger", source: "McDonald's" },
  { name: "McDonald's McDouble", category: "lunch", cal: 400, protein: 22, carbs: 35, fat: 19, serving: "1 burger", source: "McDonald's" },
  { name: "McDonald's 10-piece Chicken McNuggets", category: "lunch", cal: 420, protein: 23, carbs: 26, fat: 25, serving: "10 pieces", source: "McDonald's" },
  { name: "Wendy's Baconator", category: "lunch", cal: 950, protein: 57, carbs: 46, fat: 60, serving: "1 burger", source: "Wendy's" },
  { name: "Wendy's Dave's Single", category: "lunch", cal: 590, protein: 30, carbs: 42, fat: 34, serving: "1 burger", source: "Wendy's" },
  { name: "Chick-fil-A Original Chicken Sandwich", category: "lunch", cal: 440, protein: 28, carbs: 40, fat: 19, serving: "1 sandwich", source: "Chick-fil-A" },
  { name: "Chick-fil-A Grilled Chicken Sandwich", category: "lunch", cal: 320, protein: 29, carbs: 31, fat: 7, serving: "1 sandwich", source: "Chick-fil-A" },
  { name: "Chick-fil-A Spicy Chicken Sandwich", category: "lunch", cal: 450, protein: 28, carbs: 41, fat: 20, serving: "1 sandwich", source: "Chick-fil-A" },
  { name: "Chick-fil-A Grilled Nuggets (12-count)", category: "lunch", cal: 200, protein: 38, carbs: 2, fat: 5, serving: "12 pieces", source: "Chick-fil-A" },
  { name: "Chick-fil-A 8-count Nuggets", category: "lunch", cal: 250, protein: 29, carbs: 14, fat: 11, serving: "8 pieces", source: "Chick-fil-A" },
  { name: "Taco Bell Crunchwrap Supreme", category: "lunch", cal: 530, protein: 16, carbs: 71, fat: 21, serving: "1 crunchwrap", source: "Taco Bell" },
  { name: "Taco Bell Power Menu Bowl (chicken)", category: "lunch", cal: 470, protein: 26, carbs: 50, fat: 16, serving: "1 bowl", source: "Taco Bell" },
  { name: "Taco Bell Chicken Burrito Supreme", category: "lunch", cal: 400, protein: 17, carbs: 53, fat: 14, serving: "1 burrito", source: "Taco Bell" },
  { name: "Chipotle Chicken Burrito Bowl", category: "lunch", cal: 615, protein: 51, carbs: 58, fat: 16, serving: "1 bowl", source: "Chipotle" },
  { name: "Chipotle Steak Burrito (full)", category: "lunch", cal: 1000, protein: 56, carbs: 120, fat: 34, serving: "1 burrito", source: "Chipotle" },
  { name: "PB&J Sandwich", category: "lunch", cal: 370, protein: 13, carbs: 48, fat: 14, serving: "2 slices bread", source: "Home" },
  { name: "Turkey & Cheese Sandwich (deli)", category: "lunch", cal: 380, protein: 25, carbs: 38, fat: 12, serving: "1 sandwich", source: "Home / deli" },
  { name: "Ham & Cheese Sandwich (deli)", category: "lunch", cal: 360, protein: 22, carbs: 38, fat: 12, serving: "1 sandwich", source: "Home / deli" },
  { name: "Cup Noodles / Ramen", category: "lunch", cal: 290, protein: 8, carbs: 41, fat: 11, serving: "1 cup", source: "Gas station / store" },
  { name: "Rotisserie Chicken Breast (store-bought)", category: "lunch", cal: 220, protein: 38, carbs: 0, fat: 7, serving: "1 breast", source: "Walmart / Costco" },
  { name: "Wawa Grilled Chicken Hoagie", category: "lunch", cal: 380, protein: 28, carbs: 48, fat: 8, serving: "1 hoagie", source: "Wawa" },
  { name: "Arby's Classic Roast Beef", category: "lunch", cal: 360, protein: 23, carbs: 37, fat: 14, serving: "1 sandwich", source: "Arby's" },
  { name: "Arby's Beef & Cheddar", category: "lunch", cal: 450, protein: 26, carbs: 44, fat: 20, serving: "1 sandwich", source: "Arby's" },
  { name: "Burger King Whopper", category: "lunch", cal: 660, protein: 28, carbs: 48, fat: 40, serving: "1 burger", source: "Burger King" },
  { name: "Popeyes Classic Chicken Sandwich", category: "lunch", cal: 700, protein: 28, carbs: 64, fat: 42, serving: "1 sandwich", source: "Popeyes" },
  { name: "Raising Cane's 3 Chicken Fingers", category: "lunch", cal: 340, protein: 29, carbs: 23, fat: 14, serving: "3 tenders", source: "Raising Cane's" },
  { name: "KFC Grilled Chicken Breast", category: "lunch", cal: 220, protein: 38, carbs: 0, fat: 7, serving: "1 piece", source: "KFC" },
  { name: "Gas Station Hot Dog", category: "lunch", cal: 350, protein: 10, carbs: 28, fat: 22, serving: "1 hot dog", source: "Gas station" },
  { name: "Pizza Slice (pepperoni, large NY style)", category: "lunch", cal: 285, protein: 12, carbs: 34, fat: 11, serving: "1 slice", source: "Pizzeria" },
  { name: "Pizza Slice (cheese, large NY style)", category: "lunch", cal: 250, protein: 10, carbs: 34, fat: 8, serving: "1 slice", source: "Pizzeria" },
  { name: "Leftover Pasta with Meat Sauce", category: "lunch", cal: 480, protein: 22, carbs: 62, fat: 14, serving: "2 cups", source: "Home meal prep" },
  { name: "Chinese Takeout – Chicken with Broccoli + rice", category: "lunch", cal: 580, protein: 34, carbs: 68, fat: 14, serving: "1 combo box", source: "Chinese restaurant" },
  { name: "Pulled Pork Sandwich", category: "lunch", cal: 490, protein: 32, carbs: 52, fat: 14, serving: "1 sandwich", source: "BBQ joint / home" },
  { name: "Chicken & Rice (cooler meal prep)", category: "lunch", cal: 420, protein: 45, carbs: 50, fat: 5, serving: "1 container", source: "Home meal prep" },
  { name: "Jersey Mike's Turkey Sub (mini, #7)", category: "lunch", cal: 380, protein: 24, carbs: 44, fat: 12, serving: "mini sub", source: "Jersey Mike's" },

  // ─── GAS STATION / CONVENIENCE STORE ─────────────────────────────────────
  { name: "Beef Jerky (Jack Link's 1.25oz)", category: "gas_station", cal: 100, protein: 14, carbs: 6, fat: 2, serving: "1 bag (1.25oz)", source: "Gas station / store" },
  { name: "Slim Jim (giant, 1.94oz)", category: "gas_station", cal: 150, protein: 9, carbs: 4, fat: 11, serving: "1 stick", source: "Gas station" },
  { name: "String Cheese (2 sticks)", category: "gas_station", cal: 160, protein: 14, carbs: 2, fat: 10, serving: "2 sticks", source: "Gas station / store" },
  { name: "Hard Boiled Eggs (2-pack, pre-made)", category: "gas_station", cal: 140, protein: 12, carbs: 1, fat: 10, serving: "2 eggs", source: "Gas station / Wawa" },
  { name: "Quest Protein Bar", category: "gas_station", cal: 200, protein: 21, carbs: 22, fat: 7, serving: "1 bar", source: "Gas station / store" },
  { name: "RXBar (any flavor)", category: "gas_station", cal: 210, protein: 12, carbs: 24, fat: 9, serving: "1 bar", source: "Gas station / store" },
  { name: "Clif Bar", category: "gas_station", cal: 250, protein: 9, carbs: 44, fat: 6, serving: "1 bar (2.4oz)", source: "Gas station / store" },
  { name: "Kind Bar (dark chocolate nuts)", category: "gas_station", cal: 200, protein: 6, carbs: 17, fat: 15, serving: "1 bar", source: "Gas station / store" },
  { name: "Nature Valley Protein Bar", category: "gas_station", cal: 190, protein: 10, carbs: 22, fat: 7, serving: "1 bar", source: "Gas station / store" },
  { name: "Trail Mix (1 oz)", category: "gas_station", cal: 140, protein: 4, carbs: 14, fat: 8, serving: "1 oz", source: "Gas station / store" },
  { name: "Mixed Nuts (1 oz, salted)", category: "gas_station", cal: 170, protein: 5, carbs: 6, fat: 15, serving: "1 oz", source: "Gas station / store" },
  { name: "Pistachios (1 oz, shelled)", category: "gas_station", cal: 160, protein: 6, carbs: 8, fat: 13, serving: "1 oz", source: "Gas station / store" },
  { name: "Pork Rinds (1 oz)", category: "gas_station", cal: 130, protein: 14, carbs: 0, fat: 8, serving: "1 oz bag", source: "Gas station" },
  { name: "Sunflower Seeds (1 oz, David brand)", category: "gas_station", cal: 165, protein: 6, carbs: 6, fat: 14, serving: "1 oz", source: "Gas station" },
  { name: "Banana", category: "gas_station", cal: 105, protein: 1, carbs: 27, fat: 0, serving: "1 medium", source: "Gas station / store" },
  { name: "Apple", category: "gas_station", cal: 95, protein: 0, carbs: 25, fat: 0, serving: "1 medium", source: "Gas station / store" },
  { name: "Oikos Triple Zero Greek Yogurt (5.3oz)", category: "gas_station", cal: 90, protein: 15, carbs: 8, fat: 0, serving: "1 cup (5.3oz)", source: "Gas station / store" },
  { name: "Pre-made Ham & Cheese Sandwich (packaged)", category: "gas_station", cal: 380, protein: 19, carbs: 38, fat: 16, serving: "1 sandwich", source: "Gas station / Wawa" },
  { name: "Pre-made Grilled Chicken Wrap (packaged)", category: "gas_station", cal: 340, protein: 22, carbs: 34, fat: 12, serving: "1 wrap", source: "Wawa / Sheetz" },
  { name: "Hot Dog (roller grill)", category: "gas_station", cal: 350, protein: 10, carbs: 28, fat: 22, serving: "1 hot dog in bun", source: "Gas station" },
  { name: "Taquitos (2, roller grill)", category: "gas_station", cal: 380, protein: 9, carbs: 44, fat: 18, serving: "2 taquitos", source: "Gas station" },
  { name: "Mini Donuts (powdered, 6-pack)", category: "gas_station", cal: 420, protein: 5, carbs: 58, fat: 18, serving: "6 donuts", source: "Gas station" },
  { name: "Snickers Bar (1.86oz)", category: "gas_station", cal: 250, protein: 4, carbs: 33, fat: 12, serving: "1 bar", source: "Gas station" },
  { name: "Pepperoni & Cheese Snack Pack", category: "gas_station", cal: 160, protein: 9, carbs: 4, fat: 12, serving: "1 pack", source: "Gas station / store" },
  { name: "Chocolate Milk (8oz carton)", category: "gas_station", cal: 160, protein: 8, carbs: 24, fat: 5, serving: "8oz", source: "Gas station" },
  { name: "Chips (Doritos small bag)", category: "gas_station", cal: 260, protein: 3, carbs: 34, fat: 13, serving: "1 small bag (2oz)", source: "Gas station" },
  { name: "Crackers & Cheese Snack Pack (Kraft)", category: "gas_station", cal: 160, protein: 6, carbs: 18, fat: 8, serving: "1 pack", source: "Gas station" },
  { name: "Nutri-Grain Bar", category: "gas_station", cal: 130, protein: 2, carbs: 26, fat: 3, serving: "1 bar (1.55oz)", source: "Gas station / store" },
  { name: "Monster Energy (16oz)", category: "gas_station", cal: 210, protein: 0, carbs: 54, fat: 0, serving: "1 can (16oz)", source: "Gas station" },
  { name: "Energy drink + Hot Dog combo", category: "gas_station", cal: 560, protein: 10, carbs: 82, fat: 22, serving: "combo", source: "Gas station" },

  // ─── SNACKS ───────────────────────────────────────────────────────────────
  { name: "Protein Shake (1 scoop whey + water)", category: "snacks", cal: 120, protein: 25, carbs: 3, fat: 2, serving: "1 shake", source: "Home" },
  { name: "Protein Shake (1 scoop + 8oz whole milk)", category: "snacks", cal: 270, protein: 33, carbs: 18, fat: 8, serving: "1 shake", source: "Home" },
  { name: "Premier Protein Shake RTD (11oz)", category: "snacks", cal: 160, protein: 30, carbs: 5, fat: 3, serving: "1 bottle", source: "Store / gas station" },
  { name: "Fairlife Core Power Elite (14oz)", category: "snacks", cal: 230, protein: 42, carbs: 9, fat: 3, serving: "1 bottle", source: "Store / gas station" },
  { name: "Hard Boiled Eggs (2)", category: "snacks", cal: 140, protein: 12, carbs: 1, fat: 10, serving: "2 eggs", source: "Home / gas station" },
  { name: "Hard Boiled Egg (1)", category: "snacks", cal: 70, protein: 6, carbs: 0, fat: 5, serving: "1 egg", source: "Home / gas station" },
  { name: "Greek Yogurt – Chobani Plain Non-fat (5.3oz)", category: "snacks", cal: 90, protein: 16, carbs: 6, fat: 0, serving: "1 cup (5.3oz)", source: "Store / Wawa" },
  { name: "Greek Yogurt – Chobani Flavored (5.3oz)", category: "snacks", cal: 130, protein: 12, carbs: 17, fat: 3, serving: "1 cup (5.3oz)", source: "Store / gas station" },
  { name: "Cottage Cheese (1/2 cup)", category: "snacks", cal: 110, protein: 14, carbs: 4, fat: 5, serving: "1/2 cup", source: "Home" },
  { name: "Beef Jerky (Jack Link's 1.25oz)", category: "snacks", cal: 100, protein: 14, carbs: 6, fat: 2, serving: "1 bag", source: "Store / gas station" },
  { name: "String Cheese (1 stick)", category: "snacks", cal: 80, protein: 7, carbs: 1, fat: 5, serving: "1 stick", source: "Store / gas station" },
  { name: "String Cheese (2 sticks)", category: "snacks", cal: 160, protein: 14, carbs: 2, fat: 10, serving: "2 sticks", source: "Store / gas station" },
  { name: "Beef Jerky + String Cheese combo", category: "snacks", cal: 180, protein: 21, carbs: 7, fat: 7, serving: "1 bag + 1 stick", source: "Store / gas station" },
  { name: "Apple", category: "snacks", cal: 95, protein: 0, carbs: 25, fat: 0, serving: "1 medium", source: "Store / gas station" },
  { name: "Banana", category: "snacks", cal: 105, protein: 1, carbs: 27, fat: 0, serving: "1 medium", source: "Store / gas station" },
  { name: "Orange", category: "snacks", cal: 65, protein: 1, carbs: 16, fat: 0, serving: "1 medium", source: "Store / gas station" },
  { name: "Apple + Peanut Butter (2 tbsp)", category: "snacks", cal: 290, protein: 7, carbs: 37, fat: 16, serving: "1 apple + 2 tbsp", source: "Home" },
  { name: "Mixed Nuts (1 oz)", category: "snacks", cal: 170, protein: 5, carbs: 6, fat: 15, serving: "1 oz", source: "Store / gas station" },
  { name: "Almonds (1 oz)", category: "snacks", cal: 165, protein: 6, carbs: 6, fat: 14, serving: "1 oz (23 almonds)", source: "Store / gas station" },
  { name: "Peanuts, dry roasted (1 oz)", category: "snacks", cal: 165, protein: 7, carbs: 6, fat: 14, serving: "1 oz", source: "Store / gas station" },
  { name: "Cashews (1 oz)", category: "snacks", cal: 157, protein: 5, carbs: 9, fat: 12, serving: "1 oz", source: "Store / gas station" },
  { name: "Peanut Butter Crackers (Ritz 1.38oz)", category: "snacks", cal: 200, protein: 5, carbs: 22, fat: 11, serving: "1 pack", source: "Store / gas station" },
  { name: "Clif Bar (original)", category: "snacks", cal: 250, protein: 9, carbs: 44, fat: 6, serving: "1 bar (2.4oz)", source: "Store / gas station" },
  { name: "Clif Builder's Protein Bar", category: "snacks", cal: 270, protein: 20, carbs: 34, fat: 8, serving: "1 bar (2.4oz)", source: "Store / gas station" },
  { name: "Quest Protein Cookie", category: "snacks", cal: 250, protein: 21, carbs: 25, fat: 9, serving: "1 cookie (2.04oz)", source: "Store / gas station" },
  { name: "Rice Cakes, plain (2)", category: "snacks", cal: 70, protein: 1, carbs: 14, fat: 1, serving: "2 cakes", source: "Store" },
  { name: "Rice Cakes + Peanut Butter (2)", category: "snacks", cal: 200, protein: 7, carbs: 22, fat: 10, serving: "2 cakes + 1 tbsp PB", source: "Home" },
  { name: "Tuna Packet (StarKist 2.6oz)", category: "snacks", cal: 80, protein: 17, carbs: 0, fat: 1, serving: "1 packet", source: "Store / gas station" },
  { name: "Popcorn, light (microwave bag)", category: "snacks", cal: 230, protein: 5, carbs: 42, fat: 8, serving: "1 bag", source: "Home / gas station" },
  { name: "Pork Rinds (1 oz)", category: "snacks", cal: 130, protein: 14, carbs: 0, fat: 8, serving: "1 oz bag", source: "Gas station" },
  { name: "Celery + Peanut Butter (2 tbsp)", category: "snacks", cal: 190, protein: 7, carbs: 8, fat: 14, serving: "3 stalks + 2 tbsp", source: "Home" },
  { name: "Carrots + Hummus (1/4 cup)", category: "snacks", cal: 160, protein: 5, carbs: 18, fat: 8, serving: "1 cup carrots + hummus", source: "Home / store" },

  // ─── DINNER / AFTER WORK ──────────────────────────────────────────────────
  { name: "Grilled Chicken Breast + Rice + Broccoli", category: "dinner", cal: 520, protein: 50, carbs: 56, fat: 8, serving: "1 plate", source: "Home" },
  { name: "Chicken & Rice Meal Prep Container", category: "dinner", cal: 420, protein: 45, carbs: 50, fat: 5, serving: "1 container", source: "Home meal prep" },
  { name: "Steak (6oz ribeye) + Baked Potato", category: "dinner", cal: 680, protein: 50, carbs: 46, fat: 28, serving: "6oz steak + 1 potato", source: "Home / steakhouse" },
  { name: "Sirloin Steak (6oz) + Steamed Vegetables", category: "dinner", cal: 450, protein: 46, carbs: 18, fat: 20, serving: "6oz steak + veggies", source: "Home" },
  { name: "Spaghetti with Meat Sauce", category: "dinner", cal: 580, protein: 32, carbs: 70, fat: 16, serving: "2 cups", source: "Home" },
  { name: "Ground Beef Tacos (3, corn tortilla)", category: "dinner", cal: 480, protein: 28, carbs: 42, fat: 22, serving: "3 tacos", source: "Home" },
  { name: "Chicken Tacos (3, soft flour tortilla)", category: "dinner", cal: 450, protein: 36, carbs: 44, fat: 14, serving: "3 tacos", source: "Home" },
  { name: "Turkey Taco Bowl (meal prep)", category: "dinner", cal: 450, protein: 42, carbs: 55, fat: 10, serving: "1 container", source: "Home meal prep" },
  { name: "Cheeseburger (homemade, 6oz patty)", category: "dinner", cal: 520, protein: 30, carbs: 38, fat: 28, serving: "1 burger", source: "Home" },
  { name: "Double Smash Burger (homemade)", category: "dinner", cal: 720, protein: 42, carbs: 44, fat: 40, serving: "1 burger", source: "Home" },
  { name: "Pizza Delivery (2 slices, pepperoni, medium)", category: "dinner", cal: 570, protein: 24, carbs: 68, fat: 22, serving: "2 slices", source: "Domino's / Pizza Hut" },
  { name: "Pizza Delivery (3 slices, cheese, medium)", category: "dinner", cal: 750, protein: 30, carbs: 102, fat: 24, serving: "3 slices", source: "Domino's / Pizza Hut" },
  { name: "Buffalo Wings (10, traditional)", category: "dinner", cal: 600, protein: 42, carbs: 18, fat: 42, serving: "10 wings", source: "Wingstop / home" },
  { name: "Buffalo Wings (6) + Celery Sticks", category: "dinner", cal: 420, protein: 30, carbs: 12, fat: 30, serving: "6 wings", source: "Wingstop / home" },
  { name: "Slow Cooker Pulled Pork + Coleslaw", category: "dinner", cal: 580, protein: 40, carbs: 44, fat: 22, serving: "1 plate", source: "Home" },
  { name: "Slow Cooker Pot Roast (with potatoes & carrots)", category: "dinner", cal: 520, protein: 38, carbs: 38, fat: 20, serving: "1 plate", source: "Home" },
  { name: "Slow Cooker Chili (2 cups)", category: "dinner", cal: 450, protein: 30, carbs: 46, fat: 16, serving: "2 cups", source: "Home" },
  { name: "Salmon Fillet (6oz) + Asparagus", category: "dinner", cal: 340, protein: 41, carbs: 8, fat: 16, serving: "6oz salmon + veggies", source: "Home" },
  { name: "Salmon + Rice + Broccoli", category: "dinner", cal: 580, protein: 44, carbs: 58, fat: 16, serving: "1 plate", source: "Home" },
  { name: "Baked Chicken Thighs + Sweet Potato", category: "dinner", cal: 480, protein: 38, carbs: 44, fat: 14, serving: "2 thighs + 1 potato", source: "Home" },
  { name: "Pork Chops + Green Beans", category: "dinner", cal: 420, protein: 40, carbs: 14, fat: 22, serving: "2 chops + beans", source: "Home" },
  { name: "Chicken Alfredo Pasta", category: "dinner", cal: 680, protein: 34, carbs: 76, fat: 26, serving: "2 cups", source: "Home / Olive Garden" },
  { name: "Chinese Takeout Combo (fried rice + General Tso's)", category: "dinner", cal: 780, protein: 32, carbs: 96, fat: 28, serving: "1 combo box", source: "Chinese restaurant" },
  { name: "Rotisserie Chicken (half) + Side Salad", category: "dinner", cal: 420, protein: 44, carbs: 10, fat: 22, serving: "1/2 chicken", source: "Walmart / Costco" },
  { name: "Ground Beef Stir Fry + Rice", category: "dinner", cal: 580, protein: 34, carbs: 58, fat: 20, serving: "1 plate", source: "Home" },
  { name: "Turkey Meatballs + Pasta", category: "dinner", cal: 540, protein: 36, carbs: 62, fat: 14, serving: "1 plate", source: "Home" },
  { name: "Grilled Shrimp + Rice + Veggies", category: "dinner", cal: 400, protein: 35, carbs: 48, fat: 8, serving: "1 plate", source: "Home" },
  { name: "Egg Scramble (3 eggs, peppers, onion, cheese)", category: "dinner", cal: 310, protein: 22, carbs: 8, fat: 20, serving: "1 plate", source: "Home" },
  { name: "BLT Sandwich (homemade)", category: "dinner", cal: 420, protein: 20, carbs: 36, fat: 22, serving: "1 sandwich", source: "Home" },
  { name: "Deli Turkey Wrap (lettuce, cheese, veggies)", category: "dinner", cal: 380, protein: 26, carbs: 36, fat: 14, serving: "1 wrap", source: "Home" },

  // ─── DRINKS ───────────────────────────────────────────────────────────────
  { name: "Water (16oz bottle)", category: "drinks", cal: 0, protein: 0, carbs: 0, fat: 0, serving: "16oz", source: "Anywhere" },
  { name: "Water (32oz)", category: "drinks", cal: 0, protein: 0, carbs: 0, fat: 0, serving: "32oz", source: "Anywhere" },
  { name: "Black Coffee (12oz)", category: "drinks", cal: 5, protein: 0, carbs: 1, fat: 0, serving: "12oz", source: "McDonald's / Dunkin' / gas station" },
  { name: "Coffee with Cream & Sugar (12oz)", category: "drinks", cal: 80, protein: 1, carbs: 12, fat: 3, serving: "12oz", source: "McDonald's / Dunkin'" },
  { name: "Iced Coffee with cream (16oz)", category: "drinks", cal: 120, protein: 2, carbs: 16, fat: 6, serving: "16oz", source: "Dunkin' / McDonald's" },
  { name: "Monster Energy (16oz original)", category: "drinks", cal: 210, protein: 0, carbs: 54, fat: 0, serving: "1 can (16oz)", source: "Gas station / store" },
  { name: "Monster Ultra Zero (16oz)", category: "drinks", cal: 10, protein: 0, carbs: 3, fat: 0, serving: "1 can (16oz)", source: "Gas station / store" },
  { name: "Red Bull (8.4oz)", category: "drinks", cal: 110, protein: 1, carbs: 28, fat: 0, serving: "1 can (8.4oz)", source: "Gas station / store" },
  { name: "Red Bull Sugar Free (8.4oz)", category: "drinks", cal: 10, protein: 1, carbs: 3, fat: 0, serving: "1 can (8.4oz)", source: "Gas station / store" },
  { name: "Bang Energy (16oz)", category: "drinks", cal: 0, protein: 0, carbs: 0, fat: 0, serving: "1 can (16oz)", source: "Gas station / store" },
  { name: "Gatorade (32oz)", category: "drinks", cal: 200, protein: 0, carbs: 56, fat: 0, serving: "32oz bottle", source: "Gas station / store" },
  { name: "Gatorade Zero (32oz)", category: "drinks", cal: 10, protein: 0, carbs: 2, fat: 0, serving: "32oz bottle", source: "Gas station / store" },
  { name: "Powerade (32oz)", category: "drinks", cal: 210, protein: 0, carbs: 56, fat: 0, serving: "32oz bottle", source: "Gas station / store" },
  { name: "Bodyarmor Sport Drink (16oz)", category: "drinks", cal: 90, protein: 0, carbs: 22, fat: 0, serving: "16oz", source: "Gas station / store" },
  { name: "Muscle Milk Protein Shake RTD (14oz)", category: "drinks", cal: 160, protein: 25, carbs: 8, fat: 5, serving: "14oz", source: "Gas station / store" },
  { name: "Premier Protein Shake (11oz)", category: "drinks", cal: 160, protein: 30, carbs: 5, fat: 3, serving: "11oz", source: "Gas station / store" },
  { name: "Fairlife Core Power (14oz)", category: "drinks", cal: 230, protein: 42, carbs: 9, fat: 3, serving: "14oz", source: "Gas station / store" },
  { name: "Whole Milk (8oz)", category: "drinks", cal: 150, protein: 8, carbs: 12, fat: 8, serving: "8oz", source: "Gas station / store" },
  { name: "Chocolate Milk (8oz)", category: "drinks", cal: 200, protein: 8, carbs: 30, fat: 5, serving: "8oz", source: "Gas station / store" },
  { name: "Coke / Pepsi (20oz bottle)", category: "drinks", cal: 240, protein: 0, carbs: 65, fat: 0, serving: "20oz", source: "Gas station / fast food" },
  { name: "Diet Coke / Pepsi Zero (20oz)", category: "drinks", cal: 0, protein: 0, carbs: 0, fat: 0, serving: "20oz", source: "Gas station / fast food" },
  { name: "Sweet Tea (32oz, fast food)", category: "drinks", cal: 280, protein: 0, carbs: 74, fat: 0, serving: "32oz", source: "McDonald's / Chick-fil-A" },
  { name: "Lemonade (16oz, fast food)", category: "drinks", cal: 170, protein: 0, carbs: 46, fat: 0, serving: "16oz", source: "Chick-fil-A / fast food" },
  { name: "Orange Juice (12oz)", category: "drinks", cal: 165, protein: 2, carbs: 39, fat: 0, serving: "12oz", source: "Gas station / fast food" },
];

export const MEAL_DB_CATEGORIES: { value: MealDBCategory | "all"; label: string }[] = [
  { value: "all",         label: "All" },
  { value: "breakfast",   label: "Breakfast" },
  { value: "lunch",       label: "Lunch" },
  { value: "gas_station", label: "Gas Station" },
  { value: "snacks",      label: "Snacks" },
  { value: "dinner",      label: "Dinner" },
  { value: "drinks",      label: "Drinks" },
];
