// Tonight's Play — Activity Database
// Matches on energy level, time available, and kid age ranges.

export type AgeRange = "baby" | "preschool" | "elementary" | "tween" | "teen";
export type EnergyLevel = "low" | "medium" | "high";
export type Location = "indoor" | "outdoor" | "either";

export type Activity = {
  id: string;
  name: string;
  itemsNeeded: string;
  ageRanges: AgeRange[];
  energyLevel: EnergyLevel;
  minTime: 15 | 30 | 60;
  location: Location;
  steps: string[];
  whyItMatters: string;
};

export const ACTIVITIES: Activity[] = [

  // ── LOW ENERGY + 15 MIN ──────────────────────────────────────────────────────

  {
    id: "fort-builder",
    name: "Fort Builder",
    itemsNeeded: "Couch cushions and a blanket",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Grab every couch cushion and pull them onto the floor.",
      "Drape a blanket over chairs or the couch to make a roof.",
      "Crawl inside together and just sit there.",
      "Talk about what your fort needs — a flag, a password, a secret menu.",
    ],
    whyItMatters: "You showed up. That's the whole thing. Kids don't remember the fort — they remember you were inside it with them.",
  },
  {
    id: "story-time-remix",
    name: "Story Time Remix",
    itemsNeeded: "Nothing",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Lie down on the couch or floor next to your kid.",
      "Tell them: 'Tonight, you tell me the story. I'll close my eyes and listen.'",
      "Let them go — no interrupting, no correcting.",
      "At the end, ask one question: 'What happened next?'",
    ],
    whyItMatters: "You gave them the mic. Kids light up when an adult actually listens. That's rare, and they feel it.",
  },
  {
    id: "thumb-war",
    name: "Thumb War Tournament",
    itemsNeeded: "Nothing",
    ageRanges: ["elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Show them the handshake: 'One, two, three, four, I declare a thumb war.'",
      "Best two out of three. Then best two out of three for the rematch.",
      "Add a championship round with official commentary.",
      "Loser has to pick the winner's sock color tomorrow. Keep it stupid simple.",
    ],
    whyItMatters: "It's physical contact and laughter with zero setup. You're present, and they know it.",
  },
  {
    id: "would-you-rather",
    name: "Would You Rather",
    itemsNeeded: "Nothing",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Start with a dumb one: 'Would you rather eat a bowl of ketchup or a bowl of mustard?'",
      "They answer, then it's their turn to ask you.",
      "Keep going back and forth, getting weirder each round.",
      "Try to stump each other with the hardest one you can think of.",
    ],
    whyItMatters: "You find out how your kid thinks. They find out you're a real person. Both matter.",
  },
  {
    id: "peek-a-boo",
    name: "Peek-a-Boo Marathon",
    itemsNeeded: "Nothing",
    ageRanges: ["baby", "preschool"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Sit on the floor across from them.",
      "Cover your face with your hands. Wait a beat. 'PEEK-A-BOO!'",
      "Let them try it on you — act shocked every single time.",
      "Try hiding behind a pillow, a blanket, around a doorframe.",
    ],
    whyItMatters: "At this age, your face is their whole world. Every time you reappear, you're teaching them: I come back. That's the foundation of trust.",
  },
  {
    id: "bedtime-story",
    name: "Make-Up Bedtime Story",
    itemsNeeded: "Nothing",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Lie down next to them wherever they sleep.",
      "Start: 'Once there was a kid exactly like you, and one day they found...'",
      "Let them fill in the blank — what did they find?",
      "Build the story together until one of you runs out of ideas.",
    ],
    whyItMatters: "You used your voice to make something just for them. Doesn't matter if the story is terrible. Your voice at night is safety.",
  },
  {
    id: "guess-that-sound",
    name: "Guess That Sound",
    itemsNeeded: "Nothing",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Close your eyes and make a sound — knock on the table, tap your foot, crinkle paper.",
      "They guess what made the noise.",
      "Switch — they make the sound, you guess.",
      "Walk around the house together finding new sounds to use.",
    ],
    whyItMatters: "Silly games that involve the whole body keep little kids dialed in. You made their brain work with yours.",
  },
  {
    id: "20-questions",
    name: "20 Questions",
    itemsNeeded: "Nothing",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "One person thinks of a person, place, or thing. Don't say what it is.",
      "The other gets 20 yes/no questions to figure it out.",
      "Keep score — whoever guesses with fewer questions wins.",
      "Play at least three rounds, getting harder each time.",
    ],
    whyItMatters: "You're teaching them how to think systematically without calling it a lesson. They won't even know it's happening.",
  },
  {
    id: "hand-massage",
    name: "Hand Massage + Talking",
    itemsNeeded: "A little lotion if you have it",
    ageRanges: ["baby", "preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Sit with your kid and take one of their hands.",
      "Start rubbing — palms, fingers, between the knuckles.",
      "Ask them to tell you one good thing and one hard thing from today.",
      "Just listen. Don't fix anything. Just listen.",
    ],
    whyItMatters: "Touch + focused attention is the most direct way to say 'you matter.' You don't need words for that to land.",
  },
  {
    id: "name-that-tune",
    name: "Name That Tune",
    itemsNeeded: "A phone with music",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Pull up a playlist — yours or theirs. Start every song at a random spot.",
      "First one to name the song wins a point.",
      "Alternate who controls the playlist.",
      "Last round: each person picks their favorite song and explains why.",
    ],
    whyItMatters: "You let them into your music and you got into theirs. That's a window into who they're becoming.",
  },

  // ── LOW ENERGY + 30 MIN ──────────────────────────────────────────────────────

  {
    id: "movie-snack-picnic",
    name: "Movie Snack Picnic",
    itemsNeeded: "Blankets and whatever snacks you have",
    ageRanges: ["baby", "preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Pull the cushions off the couch and spread blankets on the floor.",
      "Let your kid raid the snack cabinet — one item each, no judgment.",
      "Pick a movie together. Let them pick first.",
      "Lie on the floor with them. That's it. That's the whole thing.",
    ],
    whyItMatters: "You turned a Tuesday into a memory. Low effort, high impact. That's the whole game.",
  },
  {
    id: "draw-each-other",
    name: "Draw Each Other",
    itemsNeeded: "Paper and a pencil or pen",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Each person gets a piece of paper. You draw them. They draw you.",
      "Five minutes, no peeking.",
      "Reveal at the same time and genuinely react.",
      "Post it on the fridge. Seriously — put it up.",
    ],
    whyItMatters: "You gave them your attention and made them feel seen. The drawing proves you were there together.",
  },
  {
    id: "go-fish",
    name: "Card Game — Go Fish",
    itemsNeeded: "A deck of cards",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Deal 5 cards to each player. Rest goes in the middle face down.",
      "Take turns asking for cards. 'Got any 7s?' — if not, 'Go fish.'",
      "When you collect all four of a number, lay them down.",
      "Most sets when the deck runs out wins. Play two rounds.",
    ],
    whyItMatters: "It's a small act of routine that anchors them. Something predictable in a day full of chaos is a gift.",
  },
  {
    id: "sock-puppet-show",
    name: "Sock Puppet Show",
    itemsNeeded: "Two socks and a marker",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Grab two socks each. Draw a face on each one with a marker.",
      "Name your puppets. Make them ridiculous.",
      "Your kid does the first scene. You do the second.",
      "End with a final showdown scene. Let the kids pick the winner.",
    ],
    whyItMatters: "You made something with your hands with them. That's craft, creativity, and connection — all for free.",
  },
  {
    id: "puzzle-together",
    name: "Work a Puzzle",
    itemsNeeded: "A puzzle (any size)",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Dump it out and flip all pieces face-up.",
      "Sort edges from middle pieces. Let them sort.",
      "Work from the corners in. No assigned sections — just build.",
      "See how far you get. Leave it out so you can finish it tomorrow.",
    ],
    whyItMatters: "Working on a shared problem without pressure is surprisingly good for connection. No agenda — just work.",
  },
  {
    id: "read-together",
    name: "Read Together",
    itemsNeeded: "A book",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Let them pick the book. Even if you've read it 40 times.",
      "Read slow. Do the voices. Don't phone it in.",
      "Stop and ask what they think will happen next.",
      "After the last page: 'Was that the ending you expected?'",
    ],
    whyItMatters: "Your voice reading to them is one of the most comforting things that exists. They'll hear it in their head the rest of their lives.",
  },
  {
    id: "playdoh",
    name: "Play-Doh Free Build",
    itemsNeeded: "Play-Doh or modeling clay",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Give everyone a ball of a different color.",
      "Announce the theme: animals, food, things you'd find on a job site.",
      "Build for 15 minutes, no peeking at each other's work.",
      "Do a 'reveal' and guess what everyone made.",
    ],
    whyItMatters: "Your hands in clay next to their hands in clay. It sounds small. It isn't.",
  },
  {
    id: "coloring",
    name: "Coloring Side by Side",
    itemsNeeded: "Coloring pages or paper, crayons or markers",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Grab a coloring book or print free pages from anywhere.",
      "Each person takes a page — same image or different.",
      "Sit next to each other and color. No instructions. No judgment on the colors.",
      "Frame the best ones on the fridge when done.",
    ],
    whyItMatters: "Side-by-side presence, no pressure — that's where the real conversations sneak out.",
  },
  {
    id: "family-photos",
    name: "Family Photo Walk",
    itemsNeeded: "Your phone",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "either",
    steps: [
      "Hand them your phone or let them use their own.",
      "Challenge: get 10 photos of things that matter to you — anywhere inside or outside.",
      "No phones during the walk except for photos.",
      "Look through them together at the end. Ask them about the ones they chose.",
    ],
    whyItMatters: "You saw the world through their eyes for 30 minutes. What they photograph tells you who they are right now.",
  },
  {
    id: "evening-drive",
    name: "Evening Drive to Nowhere",
    itemsNeeded: "Keys and a car",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "either",
    steps: [
      "Load them up. No destination.",
      "Let them control the radio or playlist.",
      "Drive around. Stop for a slushie or a snack if something's open.",
      "On the way home: 'What's one thing you want to do this weekend?'",
    ],
    whyItMatters: "The car is one of the few places where kids talk because they're not facing you. Use that.",
  },

  // ── LOW ENERGY + 60 MIN ──────────────────────────────────────────────────────

  {
    id: "backyard-stargazing",
    name: "Backyard Stargazing",
    itemsNeeded: "Blanket and your backyard",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Grab the biggest blanket you have and lay it outside flat.",
      "Lie down next to your kid and look up.",
      "Point out the brightest star you can see. Ask them to find a brighter one.",
      "Tell them one true thing about your day you haven't told anyone.",
    ],
    whyItMatters: "The sky makes everything feel bigger and the problems smaller. You gave them that perspective together.",
  },
  {
    id: "legos",
    name: "Legos — Free Build Challenge",
    itemsNeeded: "Legos, blocks, or whatever building set you have",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Dump the bin out. No instructions tonight — free build.",
      "Announce the challenge: 'Build the tallest thing that won't fall.'",
      "Build side by side. No helping unless they ask.",
      "Test them. Blow on them. Poke them. See what holds.",
    ],
    whyItMatters: "You built something next to them. That's what a father does on a job site — builds things. They saw that.",
  },
  {
    id: "family-movie-night",
    name: "Family Movie Night",
    itemsNeeded: "TV and popcorn if you have it",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Let each kid vote for a movie. Do a coin flip if there's a tie.",
      "Make or grab snacks together — even just crackers and cheese.",
      "Phones stay off the whole movie. No exceptions.",
      "Stay awake for the whole thing. Ask one question about it after.",
    ],
    whyItMatters: "You chose them over everything else calling your name tonight. They will never forget that you showed up.",
  },
  {
    id: "board-game-night",
    name: "Board Game Night",
    itemsNeeded: "Any board game",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Let them pick the game — no vetoing unless it's literally impossible.",
      "Actually read the rules if you don't know them.",
      "No phones during play. Not even between turns.",
      "Winner gets to pick breakfast tomorrow.",
    ],
    whyItMatters: "Structured competition with rules is how kids learn to win, lose, and play fair. You're the model for all three.",
  },
  {
    id: "simple-baking",
    name: "Bake Something Simple",
    itemsNeeded: "Boxed mix or basic ingredients for cookies/brownies",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Pick the simplest thing you can make — boxed brownies or slice-and-bake cookies work.",
      "Give them one real job: stir, measure, pour.",
      "Set the timer together. Let them watch the oven light.",
      "Eat the results while they're still warm.",
    ],
    whyItMatters: "You made something with your hands with them and then ate it. That's a ritual that goes back forever.",
  },
  {
    id: "family-trivia",
    name: "Family Trivia Night",
    itemsNeeded: "Nothing or a trivia game",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Each person writes 5 questions from any topic they know well.",
      "Take turns as the host — read your questions, others answer.",
      "Keep score on a whiteboard or paper.",
      "Final round: everyone writes a question about your family specifically.",
    ],
    whyItMatters: "You found out what your kid considers themselves an expert in. That's a conversation starter that lasts for years.",
  },
  {
    id: "video-game-together",
    name: "Video Game Session",
    itemsNeeded: "A gaming console or computer",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Ask them to teach you their favorite game — from scratch.",
      "Be genuinely bad at it. Don't fake it.",
      "Ask questions: 'What does that do? Why did you do that?'",
      "Let them show off. That's the whole point.",
    ],
    whyItMatters: "You stepped into their world and let them be the expert. That kind of humility from a parent is unforgettable.",
  },
  {
    id: "science-experiment",
    name: "Kitchen Science",
    itemsNeeded: "Baking soda, vinegar, food coloring (optional)",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Set up a tray with baking soda spread out flat.",
      "Mix vinegar with food coloring in a small cup — one color per kid if possible.",
      "Let them drip it on and watch it foam.",
      "Try different amounts and combinations. Ask 'What do you think will happen if...?'",
    ],
    whyItMatters: "You did science together in your kitchen. They might not remember what caused the reaction — but they'll remember you were curious with them.",
  },

  // ── MEDIUM ENERGY + 15 MIN ───────────────────────────────────────────────────

  {
    id: "dance-party",
    name: "Dance Party",
    itemsNeeded: "A phone with speakers",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Let them pick the first song — no vetoing.",
      "Actually dance. No standing with your arms crossed.",
      "Call out moves: 'Freeze!' then go again. 'Slow motion!' then go again.",
      "You pick the last song. Make it a good one.",
    ],
    whyItMatters: "You were silly with them. That's trust-building disguised as embarrassment.",
  },
  {
    id: "piggyback-races",
    name: "Piggyback Races",
    itemsNeeded: "A hallway or backyard",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "either",
    steps: [
      "Pick a start and finish line — end of the hall, end of the yard.",
      "Load them up. Run to the finish line.",
      "Let them 'race' each other on your back in rounds.",
      "Let the youngest one win the championship.",
    ],
    whyItMatters: "You carried them — literally. That's what they need to know you'll do.",
  },
  {
    id: "hide-and-seek",
    name: "Hide and Seek",
    itemsNeeded: "Nothing",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "You're it first. Count to 20 out loud while they hide.",
      "Take longer than necessary to find them. Let them think they really got you.",
      "Celebrate when you find them like it's the best hiding spot you've ever seen.",
      "Switch. Actually hide in a spot they won't expect.",
    ],
    whyItMatters: "You let them beat you a little and they loved it. That's good parenting wrapped in a game.",
  },
  {
    id: "simon-says",
    name: "Simon Says",
    itemsNeeded: "Nothing",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Start easy: 'Simon says pat your head.'",
      "Slowly speed up the commands. Throw in traps.",
      "When they catch you making a mistake, make it dramatic — fall on the ground.",
      "Let them be Simon for the last round.",
    ],
    whyItMatters: "They were in charge for a minute, and you played by their rules. That matters more than you know.",
  },
  {
    id: "balloon-keep-up",
    name: "Balloon Keep-Up",
    itemsNeeded: "One or two balloons",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Blow up a balloon. Simple rule: don't let it touch the floor.",
      "Count how long you can keep it up — that's your score to beat.",
      "Add rules each round: no hands, then only heads, then only feet.",
      "Try two balloons at once for the final round.",
    ],
    whyItMatters: "Stupid simple and genuinely fun. Laughing together in the living room is exactly what this family needed tonight.",
  },
  {
    id: "floor-is-lava",
    name: "Floor Is Lava",
    itemsNeeded: "Couch cushions and pillows",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Scatter cushions and pillows around the room.",
      "Call it: 'The floor is lava. You have 10 seconds!'",
      "Get off the floor yourself — play fully.",
      "Throw out challenges: 'Get to the kitchen without touching lava.'",
    ],
    whyItMatters: "You trashed the living room a little and didn't care. That's the version of you they brag about to their friends.",
  },
  {
    id: "freeze-tag",
    name: "Freeze Tag",
    itemsNeeded: "Open space — backyard or living room",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "either",
    steps: [
      "One person is 'it.' Tagged players freeze in place.",
      "Others can unfreeze frozen players by tapping them.",
      "Switch who's 'it' every few minutes.",
      "Final round: Dad is 'it' for a full two minutes.",
    ],
    whyItMatters: "Physical play where you're the 'villain' they're running from is some of the most joyful time you'll spend. Run hard.",
  },
  {
    id: "jump-rope-tricks",
    name: "Jump Rope Challenge",
    itemsNeeded: "A jump rope",
    ageRanges: ["elementary", "tween"],
    energyLevel: "medium",
    minTime: 15,
    location: "either",
    steps: [
      "Start with a basic count — who can do the most without stopping?",
      "Add challenge rounds: eyes closed, one foot, double-unders.",
      "Let them teach you a jump rope rhyme if they know one.",
      "Final challenge: beat your own best count.",
    ],
    whyItMatters: "You competed seriously and didn't sandbag it. Kids want to feel like they beat the real version of you.",
  },
  {
    id: "shadow-puppets",
    name: "Shadow Puppet Show",
    itemsNeeded: "A flashlight or phone flashlight",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Turn the lights off. Hold the flashlight against a blank wall.",
      "Make basic shapes — duck, rabbit, dog. Look them up if you need to.",
      "Let them make a shape and you guess what it is.",
      "Build a two-minute puppet show together. Any story.",
    ],
    whyItMatters: "You turned off the lights and made something out of nothing. That's magic to a kid, and you were the one who made it.",
  },

  // ── MEDIUM ENERGY + 30 MIN ───────────────────────────────────────────────────

  {
    id: "bike-ride",
    name: "Bike Ride Around the Block",
    itemsNeeded: "Bikes and helmets",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Pump the tires up if needed. Takes two minutes.",
      "Set the rule: stay together, no riding ahead.",
      "Stop at one point and point out something you notice — a house, a tree, the sky.",
      "Race the last stretch home. Let them win.",
    ],
    whyItMatters: "You took them outside and moved through the world together. That's a ritual. Rituals build families.",
  },
  {
    id: "catch",
    name: "Catch in the Yard",
    itemsNeeded: "A ball or frisbee",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Grab whatever you can throw — ball, frisbee, rolled-up sock.",
      "Start close. No pressure. Just throw back and forth.",
      "Step back a little each few throws.",
      "Don't coach. Just throw and catch and talk if something comes up.",
    ],
    whyItMatters: "The best conversations with kids happen when you're both looking away from each other. Catch creates that.",
  },
  {
    id: "water-balloon",
    name: "Water Balloon Fight",
    itemsNeeded: "Water balloons or a hose",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Fill a bag of balloons or just grab the hose.",
      "Call a truce zone — the porch or front steps.",
      "Announce the rules: no faces, no running into the street.",
      "Get hit. Actually get hit. Don't dodge everything.",
    ],
    whyItMatters: "You got wet with them. You let go. That's the version of you they need to see.",
  },
  {
    id: "treasure-hunt",
    name: "Treasure Hunt",
    itemsNeeded: "Paper and a small prize — a snack, a dollar, anything",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "indoor",
    steps: [
      "While they're not watching, hide a small prize anywhere in the house.",
      "Write 3–5 clues on slips of paper, each pointing to the next.",
      "Hand them clue #1 and send them off.",
      "Make the last clue lead to you — sitting with the prize.",
    ],
    whyItMatters: "You made the house an adventure and put yourself at the end of it. That's the whole metaphor.",
  },
  {
    id: "sidewalk-chalk",
    name: "Sidewalk Chalk Murals",
    itemsNeeded: "Sidewalk chalk",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Get the chalk out and claim your section of driveway.",
      "Each person draws their dream house, car, or something from their day.",
      "Walk through each other's drawings and ask one question about each piece.",
      "Sign everything. These are real works of art.",
    ],
    whyItMatters: "You made something that will still be there in the morning. Permanence matters, even temporary permanence.",
  },
  {
    id: "mini-golf",
    name: "Mini Golf in the Hall",
    itemsNeeded: "A ball, a stick, cups or containers",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "indoor",
    steps: [
      "Set up 5 holes using cups, toilet paper rolls, or containers as targets.",
      "Use a spatula, ruler, or foam bat to putt.",
      "Keep official score — write it down.",
      "Par is whatever you decide it is. Celebrate every hole-in-one like it's the masters.",
    ],
    whyItMatters: "You engineered something fun out of stuff lying around the house. That's a construction mindset applied at home. They see that.",
  },
  {
    id: "frisbee-yard",
    name: "Frisbee in the Yard",
    itemsNeeded: "A frisbee",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Start with basics — flat throw, back and forth.",
      "Move to 'ultimate' rules: one step after catching, must pass to score.",
      "Set up targets to aim at.",
      "End with a trick throw contest — anything goes.",
    ],
    whyItMatters: "Frisbee is one of the few sports where it doesn't matter if you're athletic. You just throw it. That levels the field.",
  },
  {
    id: "bowling-hallway",
    name: "Hallway Bowling",
    itemsNeeded: "Empty plastic bottles and a ball",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "medium",
    minTime: 30,
    location: "indoor",
    steps: [
      "Line up 10 empty bottles at the end of a hallway.",
      "Use a rubber ball or rolled-up socks to bowl.",
      "Keep score. Reset after every turn.",
      "Winner gets to pick tonight's bedtime snack.",
    ],
    whyItMatters: "You turned the hallway into a bowling alley. The house just became more interesting because you were in it.",
  },
  {
    id: "catch-fireflies",
    name: "Catch Fireflies",
    itemsNeeded: "A jar with holes in the lid",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Head out after dark with a mason jar.",
      "Hunt slow — teach them to spot the blink pattern.",
      "Catch a few together in the jar.",
      "Watch them glow for a few minutes, then let them go.",
    ],
    whyItMatters: "You took them into the dark and made it magical instead of scary. That's worth more than you know.",
  },

  // ── MEDIUM ENERGY + 60 MIN ───────────────────────────────────────────────────

  {
    id: "cook-dinner",
    name: "Cook Dinner Together",
    itemsNeeded: "Whatever food is in the house",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 60,
    location: "indoor",
    steps: [
      "Pick the simplest meal you can make together — eggs, pasta, sandwiches.",
      "Give them one real job: stir this, chop this (age-appropriate), pour this.",
      "Eat it at the table with the TV off.",
      "Ask them to rate the meal out of 10. Be prepared to defend your technique.",
    ],
    whyItMatters: "You showed them how to feed themselves and let them be useful. That's dignity. That's parenting.",
  },
  {
    id: "backyard-camping",
    name: "Backyard Camping Setup",
    itemsNeeded: "Tent or blankets, flashlights",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Drag a tent out or just layer blankets on the lawn.",
      "Get flashlights. Let them control the flashlights — always.",
      "Bring snacks out and lie there looking at the sky.",
      "Tell them a story about when you were a kid. A real one.",
    ],
    whyItMatters: "You made your own backyard an adventure. The world is big, but tonight it was yours.",
  },
  {
    id: "build-birdhouse",
    name: "Build a Birdhouse",
    itemsNeeded: "Scrap wood, nails, hammer (or a kit)",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 60,
    location: "either",
    steps: [
      "Find scraps in the garage or grab a cheap kit.",
      "Let them do as much of the nailing and measuring as possible.",
      "Don't redo their crooked work. Crooked is fine. It's theirs.",
      "Put it up somewhere in the yard when it's done.",
    ],
    whyItMatters: "You built something together that will still be standing next year. That's legacy, not just an evening.",
  },
  {
    id: "paint-rocks",
    name: "Paint Rocks",
    itemsNeeded: "Rocks from outside, paint or markers",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 60,
    location: "either",
    steps: [
      "Go outside first and find rocks together — at least 3 per person.",
      "Wash and dry them. Then set up with paint or markers.",
      "Paint anything — animals, patterns, messages, faces.",
      "Hide them around the neighborhood for strangers to find. Or keep them.",
    ],
    whyItMatters: "You made something and then released it into the world together. Small act, wide reach.",
  },
  {
    id: "nature-walk",
    name: "Nature Walk Collection",
    itemsNeeded: "A bag or bucket",
    ageRanges: ["baby", "preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Head out with a bag. Mission: collect 10 interesting things from nature.",
      "Go slow. Let them stop and look at whatever they want.",
      "Bring the collection home and identify everything you can.",
      "Display it on a shelf or windowsill. Give the collection a name.",
    ],
    whyItMatters: "You showed them how to pay attention to small things. That's a skill that transfers to everything.",
  },
  {
    id: "scavenger-hunt",
    name: "Neighborhood Scavenger Hunt",
    itemsNeeded: "Paper and pen for the list",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Write a list of 10 things to find: a red door, a dog, something that makes noise, etc.",
      "Walk the neighborhood together, checking off items.",
      "First person to spot each item gets the point.",
      "End somewhere good — an ice cream place, a park, or just home.",
    ],
    whyItMatters: "You turned a walk into a mission. That's what good leaders do — make the ordinary feel like it matters.",
  },
  {
    id: "car-wash",
    name: "Wash the Car Together",
    itemsNeeded: "Hose, bucket, soap, sponges",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Let them fill the bucket and add the soap.",
      "Give everyone a sponge or rag. Assign sections.",
      "Rinse as a team. Let them control the hose.",
      "Dry it off and step back to check the work together.",
    ],
    whyItMatters: "You taught them that things you own are worth taking care of. And you did it as a crew — the same way you run your job.",
  },
  {
    id: "teach-a-skill",
    name: "Teach a Job Site Skill",
    itemsNeeded: "Whatever tools you have — tape measure, level, hammer",
    ageRanges: ["tween", "teen"],
    energyLevel: "medium",
    minTime: 60,
    location: "either",
    steps: [
      "Pick one real skill: how to read a tape measure, how to drive a nail square, how to use a level.",
      "Show them slowly, explaining each step like they're your apprentice.",
      "Let them try it. Don't touch it. Let them fail and try again.",
      "When they get it right, tell them they got it right.",
    ],
    whyItMatters: "You gave them a skill that will last their whole life, and you gave it to them personally. That's a gift from a father.",
  },

  // ── HIGH ENERGY + 15 MIN ─────────────────────────────────────────────────────

  {
    id: "wrestling",
    name: "Wrestling Match",
    itemsNeeded: "A soft floor or grass",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 15,
    location: "either",
    steps: [
      "Establish the rules: nothing above the shoulders, no biting, tap out means stop.",
      "Start on your knees to make it fair.",
      "Let them get you down a couple times. Ham it up.",
      "Call a championship round and let them win it clean.",
    ],
    whyItMatters: "Roughhousing teaches kids where their body ends and someone else's begins. You also just laughed together.",
  },
  {
    id: "race-mailbox",
    name: "Race to the Mailbox",
    itemsNeeded: "A driveway or front path",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "high",
    minTime: 15,
    location: "outdoor",
    steps: [
      "Line up at the front door.",
      "Give them a head start — a real one, not a fake one.",
      "Sprint. Actually sprint.",
      "Make the rematch different: backwards, hopping on one foot, bear crawl.",
    ],
    whyItMatters: "You ran with them. Your kid will tell their kids about the times you raced. That's not nothing.",
  },
  {
    id: "obstacle-course",
    name: "Obstacle Course",
    itemsNeeded: "Pillows, chairs, tape, and anything in the living room",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "high",
    minTime: 15,
    location: "indoor",
    steps: [
      "Set up a course in 3 minutes: crawl under the table, jump over cushions, spin three times.",
      "Time them with your phone. Official announcements required.",
      "Run it yourself. Let them time you and give commentary.",
      "Let them redesign it for a final round.",
    ],
    whyItMatters: "You made their house a playground. They'll destroy the couch cushions doing this for weeks. Worth it.",
  },
  {
    id: "pillow-fight",
    name: "Pillow Fight",
    itemsNeeded: "Pillows",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "high",
    minTime: 15,
    location: "indoor",
    steps: [
      "Announce it. Don't surprise attack.",
      "One rule: nothing above the neck, nothing breakable in the way.",
      "Make alliances if there's more than one kid.",
      "End with a 'truce pile' — everyone falls into a pillow pile together.",
    ],
    whyItMatters: "You let them hit you with a pillow and you laughed. That's more therapeutic than it sounds.",
  },
  {
    id: "jumping-jacks-challenge",
    name: "Jumping Jacks Challenge",
    itemsNeeded: "Nothing",
    ageRanges: ["elementary", "tween"],
    energyLevel: "high",
    minTime: 15,
    location: "indoor",
    steps: [
      "Set a timer for 60 seconds. Count how many each person can do.",
      "Rest 30 seconds. Do it again — beat your score.",
      "Add push-ups, burpees, or mountain climbers for extra rounds.",
      "Write down the scores. These are official records now.",
    ],
    whyItMatters: "You worked out with them. That's how they learn that physical effort is normal and worth it.",
  },
  {
    id: "tag",
    name: "Tag — You're It",
    itemsNeeded: "Open space",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "high",
    minTime: 15,
    location: "outdoor",
    steps: [
      "Basic tag first: you're it. Chase them.",
      "Round two: reverse tag — if tagged, you're both 'it' until everyone is.",
      "Cartwheel tag: you have to do a cartwheel (or try to) after tagging someone.",
      "One minute grace period to catch your breath. Then the kids are it.",
    ],
    whyItMatters: "You ran after them. That's all it takes. Be the person who chases them — they'll run toward you for the rest of their lives.",
  },
  {
    id: "burpee-battle",
    name: "Burpee Battle",
    itemsNeeded: "Nothing",
    ageRanges: ["tween", "teen"],
    energyLevel: "high",
    minTime: 15,
    location: "indoor",
    steps: [
      "Explain and demo the burpee — don't skip form.",
      "First to 10 wins. No stopping.",
      "Rest 2 minutes. Race to 15 this time.",
      "Talk trash. Keep it funny. Last one wins the remote tonight.",
    ],
    whyItMatters: "You competed physically with your teenager. That's one of the few arenas left where you can meet as equals. Use it.",
  },

  // ── HIGH ENERGY + 30 MIN ─────────────────────────────────────────────────────

  {
    id: "kickball",
    name: "Kickball in the Yard",
    itemsNeeded: "Any rubber ball, open space",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Mark bases with whatever you have — shoes, sticks, bags.",
      "Pitcher rolls, batter kicks, everyone fields.",
      "Three outs per side. Keep it moving.",
      "Last inning: whoever's team scores wins the post-game high five ceremony.",
    ],
    whyItMatters: "You played ball with your kids. That's the stuff. Don't analyze it.",
  },
  {
    id: "basketball",
    name: "Basketball Shootout",
    itemsNeeded: "Basketball and a hoop",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Warm up with Horse — take turns calling shots.",
      "Move to a free throw competition: 5 shots each, keep score.",
      "End with a trick shot contest — anything goes.",
      "Winner picks dinner tomorrow.",
    ],
    whyItMatters: "You competed with them and they saw you try. Effort in front of your kids is worth more than victory.",
  },
  {
    id: "playground",
    name: "Playground Trip",
    itemsNeeded: "Keys and five minutes to drive",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Load up the car. No excuses.",
      "When you get there: get on the equipment with them.",
      "Push the swings. Actually push — don't just stand there.",
      "Race them home from the parking lot.",
    ],
    whyItMatters: "You drove them somewhere just for fun on a regular weeknight. That's not small.",
  },
  {
    id: "soccer",
    name: "Soccer in the Yard",
    itemsNeeded: "A soccer ball and something for goals",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Set up goals — cones, shoes, or sticks work.",
      "First to 5 goals wins. No hands.",
      "Switch to a skills challenge: juggling, dribble course.",
      "Final penalty shootout. Everybody gets 3 kicks. Best percentage wins.",
    ],
    whyItMatters: "You competed seriously and you both know it. That's respect — and it flows both ways on the field.",
  },
  {
    id: "relay-races",
    name: "Relay Races",
    itemsNeeded: "Open yard, a baton (stick, tube, anything)",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Set a start and turn-around cone or marker.",
      "Race one: straight sprint with baton pass.",
      "Race two: one leg hop.",
      "Race three: everyone holds hands — team run.",
    ],
    whyItMatters: "Team events, even tiny ones, build a sense of 'we.' You're building a team at home.",
  },
  {
    id: "hula-hoop",
    name: "Hula Hoop Challenge",
    itemsNeeded: "One or more hula hoops",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 30,
    location: "either",
    steps: [
      "Basic spin — count how many seconds each person can keep it going.",
      "Challenge: pass the hoop around the family in a circle holding hands.",
      "Toss it in the air and catch it before it hits the ground.",
      "Final round: Dad goes first. No excuses for failing.",
    ],
    whyItMatters: "You failed in front of them and kept trying. That lesson is worth every embarrassing second.",
  },
  {
    id: "four-square",
    name: "Four Square",
    itemsNeeded: "Chalk and a rubber ball",
    ageRanges: ["elementary", "tween"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Chalk four equal squares on the driveway. Number them 1–4.",
      "One person per square. Bounce and hit the ball into another square.",
      "If it bounces twice in your square without you hitting it, you're out.",
      "Rotate positions. King of the hill — stay in square 4 longest.",
    ],
    whyItMatters: "Old school playground game, nothing needed but chalk and a ball. You remembered how to play. That counts.",
  },

  // ── MEDIUM ENERGY + 15 MIN (continued) ──────────────────────────────────────

  {
    id: "mirror-game",
    name: "Mirror Game",
    itemsNeeded: "Nothing",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Stand facing each other, about arm's length apart.",
      "One person is the mirror — they copy every move the other makes.",
      "Go slow at first: raise your arm, tilt your head, wiggle your fingers.",
      "Switch who leads every minute. See who can stump the other.",
    ],
    whyItMatters: "You gave them your full attention and copied them. Being truly mirrored by a parent builds confidence in a way that can't be faked.",
  },
  {
    id: "karaoke",
    name: "Kitchen Karaoke",
    itemsNeeded: "A phone and something to use as a mic",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Pull up lyrics on your phone for a song they know.",
      "Grab a spatula, a TV remote — anything for a mic.",
      "Perform it. Fully. Don't half-do it.",
      "They pick a song for you next. No vetoing.",
    ],
    whyItMatters: "You were embarrassing in the best possible way. That takes guts, and kids respect it.",
  },
  {
    id: "arm-wrestling",
    name: "Arm Wrestling Tournament",
    itemsNeeded: "A table",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 15,
    location: "indoor",
    steps: [
      "Set up at the table. Official rules: elbows on the table, grip locked.",
      "Use your non-dominant arm against their dominant for fairness.",
      "Best of three. Declare a winner with a handshake.",
      "Championship round: they get to pick which arm you use.",
    ],
    whyItMatters: "You competed physically one-on-one. That's a direct line of respect between fathers and kids at any age.",
  },

  // ── LOW ENERGY + 15 MIN (continued) ─────────────────────────────────────────

  {
    id: "memory-game",
    name: "Memory Card Game",
    itemsNeeded: "A deck of cards",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Spread 20 cards face-down in a 4x5 grid.",
      "Take turns flipping two cards. Match = keep them. No match = flip back.",
      "Most pairs at the end wins.",
      "Play a second round — you'll both be faster this time.",
    ],
    whyItMatters: "Simple games where focus pays off teach kids that trying harder actually works.",
  },
  {
    id: "tell-me-three-things",
    name: "Tell Me Three Things",
    itemsNeeded: "Nothing",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Sit next to them — couch, floor, wherever.",
      "Say: 'Tell me three things that happened today. Anything.'",
      "Don't jump in while they talk. Just listen and nod.",
      "After they finish, share your three. Be honest — not just the good stuff.",
    ],
    whyItMatters: "You created a ritual of honest sharing. Kids who know their parent wants to hear their day will keep talking well into their teens.",
  },
  {
    id: "two-truths-lie",
    name: "Two Truths and a Lie",
    itemsNeeded: "Nothing",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Each person thinks of two true things and one lie about themselves.",
      "Say all three. The other person has to guess which is the lie.",
      "The weirder the truths, the harder the game — go for it.",
      "Keep going until someone runs out of true things.",
    ],
    whyItMatters: "You learned something real about each other. Every round of this game is a story you didn't know yet.",
  },

  // ── LOW ENERGY + 30 MIN (continued) ─────────────────────────────────────────

  {
    id: "write-letters",
    name: "Write Letters to Each Other",
    itemsNeeded: "Paper and pens",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Each person gets paper and a pen. Sit at the same table.",
      "You write a letter to them. They write one to you.",
      "No rules — it can be serious, funny, whatever feels right.",
      "Exchange and read silently. No comments required. Just read.",
    ],
    whyItMatters: "A letter from you will outlast this night by decades. They'll find it later and remember who you were.",
  },
  {
    id: "origami",
    name: "Origami Together",
    itemsNeeded: "Paper — any kind works",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Look up a simple design together — paper crane, airplane, frog.",
      "Follow the steps at the same pace. Don't race ahead.",
      "When someone gets stuck, figure it out together.",
      "When it's done, name it and keep it somewhere.",
    ],
    whyItMatters: "You solved a small problem together from start to finish. That's a complete loop — and it feels good for both of you.",
  },

  // ── MEDIUM ENERGY + 30 MIN (continued) ──────────────────────────────────────

  {
    id: "driveway-sports",
    name: "Driveway Shootout",
    itemsNeeded: "A ball and chalk for targets",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Chalk targets on the garage door — circles, zones, numbers.",
      "Take turns throwing, kicking, or bouncing the ball at the targets.",
      "Keep score. Assign point values to each zone.",
      "Last round: eyes closed. Highest score wins.",
    ],
    whyItMatters: "You competed in a game you built together from nothing. That's ingenuity. They saw it come from you.",
  },
  {
    id: "gardening",
    name: "Plant Something Together",
    itemsNeeded: "A pot, soil, and seeds or a small plant",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "medium",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Pick a pot and fill it with soil. Let them pack it in.",
      "Plant a seed or starter — something they'll be able to watch grow.",
      "Label it with both your names and today's date.",
      "Put it somewhere visible and agree to check on it together every few days.",
    ],
    whyItMatters: "You planted something living and put your names on it together. Every time they check on it, they'll think of this night.",
  },

  // ── HIGH ENERGY + 30 MIN (continued) ────────────────────────────────────────

  {
    id: "dodgeball",
    name: "Dodgeball",
    itemsNeeded: "A soft ball and open space",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Mark out a boundary — anything works.",
      "One person starts with the ball. Throw it to hit the others below the waist.",
      "If you catch a throw, the thrower is out. If it hits you, you're out.",
      "Last one standing is champion. Play best of five.",
    ],
    whyItMatters: "You played a game where they could actually get you. They will. And they'll love it.",
  },
  {
    id: "capture-the-flag",
    name: "Capture the Flag",
    itemsNeeded: "Two bandanas or towels, open yard",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Split into two teams. Divide the yard into two territories.",
      "Each team hides their flag somewhere visible in their territory.",
      "Cross into enemy territory to grab the flag. Tagged = frozen until a teammate frees you.",
      "First team to bring the flag back to their side wins.",
    ],
    whyItMatters: "You played a game with real stakes and running and strategy. That's one of the best things you can do on a weeknight.",
  },
  {
    id: "tennis-wall",
    name: "Tennis or Wall Ball",
    itemsNeeded: "A ball and a wall",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 30,
    location: "outdoor",
    steps: [
      "Find a flat wall — garage, house side, fence.",
      "Take turns hitting the ball against it — bounce-hit, bounce-hit.",
      "First person to miss loses the rally. Keep score.",
      "Winner gets to set the rules for the next game.",
    ],
    whyItMatters: "You competed in something that requires focus and quick reaction. They saw you locked in. That's presence.",
  },

  // ── HIGH ENERGY + 15 MIN (continued) ────────────────────────────────────────

  {
    id: "push-up-challenge",
    name: "Push-Up Challenge",
    itemsNeeded: "Nothing",
    ageRanges: ["tween", "teen"],
    energyLevel: "high",
    minTime: 15,
    location: "indoor",
    steps: [
      "Demonstrate proper push-up form. No skipping this step.",
      "Count reps out loud together. Stop at the same time.",
      "Rest 60 seconds. Try to beat your number.",
      "Final round: slow push-ups — 3 seconds down, 3 seconds up. Quality over quantity.",
    ],
    whyItMatters: "You trained together. That's a bonding ritual that works at any age — and they'll remember you were the one who showed them.",
  },
  {
    id: "parkour",
    name: "Backyard Parkour",
    itemsNeeded: "Whatever's in the yard — stumps, benches, walls",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 15,
    location: "outdoor",
    steps: [
      "Walk the yard and point out things to jump on, over, or around.",
      "Design a route: step on the stump, hop the curb, roll under the fence rail.",
      "Walk it once slow, then run it full speed.",
      "Add one new obstacle each round until someone bails.",
    ],
    whyItMatters: "You made the yard into a course and ran it with them. Physical exploration with a parent builds risk tolerance — the healthy kind.",
  },

  // ── HIGH ENERGY + 60 MIN ─────────────────────────────────────────────────────

  {
    id: "fishing",
    name: "Fishing Trip",
    itemsNeeded: "Fishing gear and a local spot",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Pack light. Rod, bait, bucket. Five minutes tops.",
      "Let them bait their own hook with help if needed.",
      "No phones. If you catch something, release it together.",
      "On the drive home, tell them one thing you're proud of about them.",
    ],
    whyItMatters: "You were still for an hour with your kids. In construction, stillness is rare. They noticed.",
  },
  {
    id: "park-adventure",
    name: "Park Adventure",
    itemsNeeded: "A local park, their running shoes",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Pick a park with a trail or open field.",
      "Set a mission: find 5 things that don't belong, or make it to the big tree.",
      "Let them lead. Follow their directions even when they're wrong.",
      "Stop somewhere and just sit. Let the silence happen.",
    ],
    whyItMatters: "You followed your kid's lead in the world. That's trust flowing both directions.",
  },
  {
    id: "swimming",
    name: "Swimming",
    itemsNeeded: "Pool, lake, or community swim center",
    ageRanges: ["baby", "preschool", "elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Get in the water. Do not sit on the edge.",
      "Play a game: Marco Polo, water tag, diving for coins.",
      "Teach them one thing — a stroke, a dive, how to float on your back.",
      "Last five minutes: just float next to each other and look up.",
    ],
    whyItMatters: "You got in the water with them. That's the whole memory. You got in.",
  },
  {
    id: "hiking",
    name: "Hiking Trail",
    itemsNeeded: "Water bottles and walking shoes",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Pick a trail that's short enough to complete without a meltdown.",
      "Let them set the pace. No rushing.",
      "Stop at one overlook or interesting spot and just breathe.",
      "Tell them something true about when you were their age.",
    ],
    whyItMatters: "You walked uphill with them and didn't quit. That's the most straightforward thing you can teach.",
  },
  {
    id: "bike-trail",
    name: "Bike Trail",
    itemsNeeded: "Bikes, helmets, water",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Find a trail or use the neighborhood — plan a 2–3 mile loop.",
      "No phones except for maps.",
      "Stop halfway and sit for 5 minutes.",
      "Time the return trip and try to beat the outbound pace.",
    ],
    whyItMatters: "You went somewhere together under your own power. That's a feeling that sticks.",
  },
  {
    id: "skateboard-practice",
    name: "Skateboard or Scooter Practice",
    itemsNeeded: "Skateboard, scooter, or rollerblades",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Find a flat spot — driveway, empty lot, smooth sidewalk.",
      "No phones. Just them on wheels and you spotting.",
      "Let them try things without jumping in to help unless they ask.",
      "If you can do it, show them something. If you can't, admit it and try anyway.",
    ],
    whyItMatters: "You stood there and let them practice something hard. Presence without interference is one of the most powerful things you can offer.",
  },
  {
    id: "car-work",
    name: "Work on the Car Together",
    itemsNeeded: "Whatever car needs doing — wash, oil, tires, cleaning",
    ageRanges: ["tween", "teen"],
    energyLevel: "high",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Pick one real task — check the oil, change a tire, detail the interior.",
      "Walk them through it as your apprentice, not just a helper.",
      "Give them the harder parts when they're ready.",
      "When it's done, tell them what you'd trust them to do solo next time.",
    ],
    whyItMatters: "You showed them how to take care of something they'll rely on. And you showed them you trust them enough to learn the real thing.",
  },

  // ── ADDITIONAL ACTIVITIES ────────────────────────────────────────────────────

  {
    id: "coin-magic",
    name: "Learn a Magic Trick",
    itemsNeeded: "A coin or a deck of cards",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Look up one simple trick on your phone — coin vanish, card force, anything.",
      "Learn it together. Practice it on each other until you both have it.",
      "Perform it on the rest of the family or whoever's home.",
      "Never reveal the secret to the audience. That's the magician's code.",
    ],
    whyItMatters: "You learned something new with them and shared a secret. Those two things alone build closeness.",
  },
  {
    id: "campfire-songs",
    name: "Campfire Songs",
    itemsNeeded: "Nothing — or a phone for lyrics",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Pick a song you knew growing up — something with a chorus they can follow.",
      "Sing it with them. Don't care how it sounds.",
      "Teach them the words and make them sing it back to you.",
      "Take turns picking songs. No skipping if you don't know it — just try.",
    ],
    whyItMatters: "Songs you sing together become the soundtrack of their childhood. You gave them that tonight.",
  },
  {
    id: "fort-and-flashlights",
    name: "Fort + Flashlights + Ghost Stories",
    itemsNeeded: "Cushions, a blanket, flashlights",
    ageRanges: ["preschool", "elementary"],
    energyLevel: "low",
    minTime: 60,
    location: "indoor",
    steps: [
      "Build the fort together — any shape, any materials available.",
      "Bring flashlights inside and turn the room lights off.",
      "Take turns telling a spooky story (kid-appropriate) inside the dark fort.",
      "End with a funny story so no one's scared before bed.",
    ],
    whyItMatters: "You created a whole world inside your living room. They'll request this for years.",
  },
  {
    id: "silly-interview",
    name: "Interview Each Other",
    itemsNeeded: "A pretend mic — a spatula, remote, anything",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "You're the interviewer first. Use any household object as a microphone.",
      "Ask them real questions: 'What do you want to be when you grow up? What's your superpower?'",
      "Let them ask you the same questions after. Answer honestly.",
      "Finish with: 'What do you wish more people knew about you?'",
    ],
    whyItMatters: "You asked them real questions and actually waited for the answers. That's rarer than it should be.",
  },
  {
    id: "penny-stomp",
    name: "Penny Toss Game",
    itemsNeeded: "A handful of coins and a cup or bowl",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "low",
    minTime: 15,
    location: "indoor",
    steps: [
      "Set a cup or bowl on the floor 5 feet away.",
      "Each person gets 10 pennies. Take turns tossing — one at a time.",
      "Most coins in the cup wins the round.",
      "Move the cup back each round. Last one to still make shots wins.",
    ],
    whyItMatters: "Tiny competitions with real stakes teach patience and focus. You modeled both — even when you missed.",
  },
  {
    id: "grilling-together",
    name: "Grill Together",
    itemsNeeded: "A grill and whatever's in the fridge",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "medium",
    minTime: 60,
    location: "outdoor",
    steps: [
      "Get the grill going. Let them help prep whatever you're cooking.",
      "Teach them fire safety: what's safe to touch, how to watch the heat.",
      "Give them tongs when it's safe to flip something.",
      "Eat outside. No phones. Just the food and each other.",
    ],
    whyItMatters: "You passed down a skill at the fire. That's as old as parenting gets. Don't underestimate it.",
  },
  {
    id: "worm-hunt",
    name: "Worm Hunt After Rain",
    itemsNeeded: "A container and a flashlight if dark",
    ageRanges: ["baby", "preschool", "elementary"],
    energyLevel: "medium",
    minTime: 15,
    location: "outdoor",
    steps: [
      "Head outside after it's rained — that's when they come up.",
      "Find as many worms as you can in 10 minutes.",
      "Count them. Put them in soil temporarily if they want to keep them.",
      "Release them all when you're done. No keeping worms inside.",
    ],
    whyItMatters: "You got in the dirt with them. There is no cleaner version of this that works as well.",
  },
  {
    id: "budget-bowling",
    name: "Paper Airplane Contest",
    itemsNeeded: "Paper",
    ageRanges: ["preschool", "elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Each person builds their best airplane design. Two minutes to build.",
      "Test flights: measure how far each one goes.",
      "Iterate — can you modify it to fly farther?",
      "Final round: accuracy contest — hit a target across the room.",
    ],
    whyItMatters: "You engineered something with your hands and tested it. That's exactly what you do at work. Let them see you do it at home.",
  },
  {
    id: "card-tricks",
    name: "Crazy Eights or War",
    itemsNeeded: "A deck of cards",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Pick one: War (flip cards, high card wins the pile) or Crazy Eights (match suit or number, 8s are wild).",
      "Teach the rules from scratch if they don't know them.",
      "Play until one person wins. No quitting in the middle.",
      "Winner picks what they want to do tomorrow after dinner.",
    ],
    whyItMatters: "Card games are a ritual as old as families. You kept it going. That matters.",
  },
  {
    id: "tug-of-war",
    name: "Tug of War",
    itemsNeeded: "An old rope or a few tied-together towels",
    ageRanges: ["preschool", "elementary", "tween"],
    energyLevel: "high",
    minTime: 15,
    location: "outdoor",
    steps: [
      "Mark a center line with chalk or a stick.",
      "Grab the rope. Best of three — first to pull the other past the line wins.",
      "Kids vs. Dad for the championship round.",
      "Let them win the last one. You don't have to let it look easy.",
    ],
    whyItMatters: "You pulled against them and then let them pull you. Strength shown and then given away — that's love.",
  },
  {
    id: "journal-together",
    name: "Journal Together",
    itemsNeeded: "Notebooks or loose paper, pens",
    ageRanges: ["elementary", "tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Each person gets paper or a notebook.",
      "Write for 10 minutes about anything — your day, something you're hoping for.",
      "Share one sentence from what you wrote — just one, nothing more than that.",
      "Keep your journals. Don't read each other's without asking.",
    ],
    whyItMatters: "You modeled that men write things down and sit with their thoughts. That's rare and powerful to witness.",
  },
  {
    id: "photo-edit",
    name: "Edit a Photo Together",
    itemsNeeded: "A phone with photos",
    ageRanges: ["tween", "teen"],
    energyLevel: "low",
    minTime: 30,
    location: "indoor",
    steps: [
      "Pull up a family photo or one from today.",
      "Let them show you how they'd edit it — filters, cropping, adjustments.",
      "Try one yourself. Let them critique it.",
      "Set the best one as your phone background.",
    ],
    whyItMatters: "You let them teach you something in their world. Being teachable by your kid is one of the highest forms of respect.",
  },
];
